### ISSUE TITLE
7d[ANN]开智上海线下书会招募

### ISSUE THREAD

**Issue by leilayanhui** [heshenxian1/OpenMindClass#13]
# 开智上海线下读书会
为延续开智部落主题阅读的优秀习惯, 计划组织上海线下读书会. 每期一个阅读主题, 开智正典为主, 定期聚会分享. 用输出倒逼输入, 期待共同志趣小伙伴的加入.

## 线下读书会玩法
- 每月一个阅读主题, 开智正典为主, 暂定与 @heshenxian1 的[开智越读会](https://github.com/heshenxian1/OpenMindClass)一致
- 交流方式以 [Github](https://github.com/) issue 为主. 聚会通知/ 书会玩法/ 读书笔记都会发布在[开智越读会](https://github.com/heshenxian1/OpenMindClass)仓库. 会员每月自行领取.
- 暂定以开智校友为主
- 线下聚会暂定每月一次, 以「主题分享」、「圆桌讨论」为主, 辅以「快速写卡片」、「三句话总结读书心得」等活动形式.
- 初步筹备阶段, 多有不周之处, 请务必发 issue 与我们探讨.

## 线下书会报名须知
- step1:  加入线上[开智越读会](https://github.com/heshenxian1/OpenMindClass)，在仓库的issue下报名，提交个人简介，并提交读书笔记。报名地址请戳：[开智越读书友会刍议-OpenMindClass](https://github.com/heshenxian1/OpenMindClass/issues/1)

```
报名格式参考

- 你的名号（各平台请统一名号、头像）
- 你的坐标（你从哪里来，要到哪里去？）
- 你的故事（你和开智的缘分，参加过什么课程？）
- 你的目标（你想从读书会获得什么？）
```
- step2:  完成当月的「线上读书会」阅读任务
- step3:  报名当月线下读书会，截止 9 月 30 日

## @heshenxian1 [开智越读会](https://github.com/heshenxian1/OpenMindClass)简单说明
主打玩法： 主题阅读

一个月三本书，一周一本书每人各选一个章节精读，一个季度三个月循环精读三本书各三个章节。 （主题阅读选定三本书，可自选相关主题一本书搭配阅读；一月三周各一章节，最后一周休息和串联整理读书卡片和心得）

一季一主题的经典共读和和一月一文章的读书笔记输出频率。输出读书笔记的同时，更重要是将阅读心得转化为行动策略，多主动参与线下线上交流，分享和实践细节正确中持续成长被动进步。

第一季主题阅读 「创造」, 在 9-11 月的第 1 周，阅读书目是[创新算法](https://book.douban.com/subject/3354596/)

**Comment by alissli** [comment]
@leilayanhui 这个招募贴调整了组块顺序之后，清晰很多，建议细节方面：
1. 9月30日前需提交报名要求的读书笔记；
2. 暂时对开智校友（开智付费学员）开放
