### ISSUE TITLE
【线下】2018年9月23日上海线下读书交流活动

### ISSUE THREAD

**Issue by chenmingio** [heshenxian1/OpenMindClass#14]
时间：2018年9月23日周日下午2点-4点

地点：黄隆泰·老茶馆(浙江中路店)，浙江中路457、459号(宁波路浙江中路交汇处)

费用：人均60元

联系人：陈铭 13764185335 

活动内容：讨论本月读书主题《创新算法》。建议大家提前准备自己的分享内容。

报名方式：本issue内回复。

**Comment by kendrazhang912** [comment]
报名参加，阿秋，15951814959

**Comment by kendrazhang912** [comment]
报名参加，阿秋，15951814959

**Comment by Irene6161** [comment]
报名参加，六一，13962195461，微信号：tara61

**Comment by leilayanhui** [comment]
报名参见, 蕙蕙, 微信号 Leila_yh

**Comment by wuyangping** [comment]
报名，wuyangping, 13761055162

**Comment by alissli** [comment]
- 名号：aliss
- 到场时间：14:00
- 分享：读书心得—临渊羡鱼，不如退而结网

**Comment by chenmingio** [comment]
## 9月23日读书会陈铭的复盘

亮点
-	阳平、黎黎准备充分，有备而来。

痛点
-	时间有点拖沓。
-	谈话主题比较松散、缺少思想的碰撞和激发。
-	当月主题TRIZ的讨论不够深入，会后参加者对TRIZ还是一知半解。

短期计划
-	快速试错改进
-	继续开展3期

总结和问题
-	组织人提前确认有哪些人准备好分享内容。分享内容可以分为本月主题和自由主题。
-	需要掌控节奏并固化为每次的规约。例如分为“分享/自由谈话/总结等环节”
-	正式环节2-3小时比较合适。
