### ISSUE TITLE
线下 | 20181001 杭州线下书会沙龙

### ISSUE THREAD

**Issue by heshenxian1** [heshenxian1/OpenMindClass#15]
## 20101001（周一）杭州开智书会沙龙

[![OpenMindHangZhouSalon_02.png (492×357)](https://raw.githubusercontent.com/heshenxian1/img/master/OpenMindHangZhouSalon_02.png)](https://raw.githubusercontent.com/heshenxian1/img/master/OpenMindHangZhouSalon_02.png)

> 一辈子很长，要跟有趣的人在一起。

一叶梧桐，天气晚来秋； 西子湖畔，友聚书添暖。

开智越读，开卷谈心。你我一起聊聊与经典的缘分，对创新的理解。

### 活动信息

*  开智越读书友沙龙
* 时间：10月01日（周一）11:00-14:00
* 地点：悦览树咖啡馆（黄龙万科中心）
——地址： 黄龙国际中心I楼1楼(文三路工专路十字路口南侧
* 人数：不多于8人
* 议程：报到-书友互动-主题探讨-合照
* 费用：AA制场地费

沙龙主题两部分：
前半部分暖场启动，主题：「你与开智正典」；
后半部分聚焦探究，主题：「时空变形」与创新。

## 报名方式

1.确定参加的小伙伴，可在本issue下留言.

*  名号：
*  微信号：
*  联系方式：

## 其他-备注

延伸阅读：
-   本季度主题阅读：[创造 | 01Season「开智越读书单」](https://github.com/heshenxian1/OpenMindClass/issues/3)
-  [【讨论】善用「时空变形」创造 · Issue #9 · heshenxian1/OpenMindClass](https://github.com/heshenxian1/OpenMindClass/issues/9)

若有疑问，可联系
联系人：何燊贤（微信：heshenxian1）

手之舞之，足之蹈之。带着你的思考和行动来分享吧。

**Comment by heshenxian1** [comment]
报名参加
* 名号：何燊贤
* 微信号：heshenxian1
* 联系方式：13082805332

**Comment by emmawdm** [comment]
- 名号：吴丹萌
- 微信号：15904932133
- 联系方式：15904932133

**Comment by Krystal-liang** [comment]
* 名号：青竹
* 微信号：Two_Bottle
* 联系方式：15209826137

**Comment by RachyJ** [comment]
* 名号：Rachel
* wechat: rachelj1985
* phone no.: 13777863687

**Comment by absir1949** [comment]
- 名号：AB
- wechat: 18768146067
- phone no.: 18768146067

**Comment by alissli** [comment]
- 名号：aliss
- wechat：45923432
- Phone No.: 一三四八二24九零32

---

## 启发

AB：过去我高估了「理性」，也高估了「自己的理性」
何教：人们往往高估了启动难度，而低估了适应的能力
AB：用Woop心理学编制卡片，给行动编程，用重复学习（必要难度）将行动内容植入心智。
许从从：写高阶模型卡片，刻意练习
Aliss：写卡片时候例子也很重要，例子是检验你是否真的理解术语（或反常识），初阶做法是用自己的语言重新组织作者的例子，高阶一点是举自己工作或者生活中的例子。
许从从：数学与认知神经科学的结合

## 众议解惑

### AB

- 什么时候做决策？
- 怎么判断现在的决策对我未来的生活有好处？

参考：将复杂性学科研究应用于管理领域的康奈夫因框架（Cynefin framework），展现多情景决策的模型和策略，其中在复杂情景中设定底线开始行动最重要。

### Rachel

- 一天读三本书的方法是否合理？
- 读书的时候，应该是完全遵循作者的思路，还是带着自己的评判？
- 输出笔记是要吸收读者所有的精华，还是只写自己感兴趣的点？

参考：主题阅读，同主题批量，三本作为绝对数量反而不够；小白没有选书品味，按前人走过的路，例如参考「开智正典」书单，参考大牛荐书，读书也是分层级的，量级跨越是必要的，应尝试下每天读10-15本书。

### 何教

- 开智正典的生活价值，比如创新算法很好，重新框定问题就能解决低层级的创新，还没有常识过更高层级的创新。

参考：高层级的创新适用于复杂系统，日常生活中是否有这样的情景？比如正在读博士，博士的课题研究方向的问题是否能分层级，有没有可能在高层级创新，并发表一篇或者数篇高质量论文？

### Aliss

- 如何养成写读书笔记的习惯？
- 如何化解「必要难度（隔6个小时写笔记）」的难度？

参考：探索自己的必要难度颗粒度，比如两小时后写笔记，换个地方写笔记，重复学习等等。

### 青竹

- 工作中不知道如何创新，比在国外时候，多很多限制。

参考：阿奇舒勒参考了20万份专利和大量的发明传记，在发明领域他有量级的背景信息。通过信息分析课的技能，找到自己工作领域的最小全局认识，建立全局观。

## 生活中的时空变形

- 越来越多的播放器支持倍速
- 杭州的钟书阁书店
- [卓璇文章「心理位移」分享](https://www.jianshu.com/p/7aca90ed3abe?from=groupmessage&isappinstalled=0)
- 互联网行业时空无限小，产品通过时空变形获利，比如电商、mooc
- 组织管理形式变化，工业时代通过研究工人具体的动作以提高效率，而现代是将决策权下放个人，比如服务业的海底捞模式，比如制造业丰田的一线员工看到质量缺陷有权停线，即便是严格管理的军队，比起十年前也更加人性化，美军的高级将领公开推「赋能」
- 线上与线下聚会
- 潜水时，水中的世界和地面不一样，感知发生变化（from丹萌）
- Rachel夫妇周末去星巴克或者安静的咖啡馆读书、学习
- 日程表的变化，农业时代人类以白天、黑夜、四季的尺度感知时间、工业时代是年、周、天再到分钟、信息时代就要「争分夺秒」
- 室内装修时可通过光线改变人对空间的感知，比如将灯光打在屋顶，感知到的空间变高；天花板上刷暗色，感知到的空间变低；改变窗户的位置、墙上的风景画、添加镜子都可以将感知的空间变大。
- 物理空间改变会影响心理空间，不妨设想下没有空间、没有时间的世界会是什么样


## 火花涌现

- 时空变形之「变形」：变形是对已有（旧有）模式的变形，对「零度」（坐标）的识别也很重要。
- Rachel的播种隐喻：分享就像播种，不是每个种子都会发芽，实际上也有很多种子当年不发芽，很多年后破土而出。
- 何教的镜头隐喻：时空变形就像给自己的视角加上了显微镜/放大镜，不同的情景下选用不同的镜头。
- 时空变形与反馈：从海底捞和丰田将决策权放至一线员工，缩短了反馈回路，也是一种时空变形。
- AB评价活动中涌现**「随机的美」**


## 活动改进

- 高信息密度交流是开智特色，组织与策划可酌情考虑控制信息密度
- 控制活动的节奏，比如主题、时间、人员参与
- 活动形式上可以拓展，比如高信息密度交流配合松散吃喝闲聊，比如情景表演、工作坊等
- 活动频次和时间可调整，比如说长假可以多聚
- 活动中曾分裂成几个小群
  - 空间是否有关系（长桌子）
  - 主持人有意识引导
  - 反向利用，设置分组讨论环节

## 自我收获及未来行动

  - 用**举例子**化解「知识的诅咒」（参考费曼学习法以及口语报告法）
  - 是否可以积累生活中的时空变形例子，配置自己的专属创新工具箱
  - 阅读主题拓展：复杂科学、网络科学、决策、数学

**Comment by absir1949** [comment]
## 启发
* 低估了《创新算法》的伟大，之前小视其为「第二序改变」，但其实不仅于此，他提出了整个物理场的创新算法，在当前信息场领域虽不能直接套用，但这是一个极其伟大的成就。

## 问题：如何做决策？

Cynefin框架  ^术语卡
	
	Cynefin框架是由威尔士学者Dave Snowden 在1999年提出的一个决策模型。这个框架用于描述环境、问题、系统。说明在什么环境下适合使用什么样的解决方案。
	
	它定义了5个域。
	
	* 简单（Simple）
	
	因果关系清晰可见，模式重复保持稳定。决策只需要按照之前的最佳实践执行即可。但要避免陷入僵固思维，忽略情况变化。
	
	* 繁杂（Complicated）
	因果关系明确，但并非人人可见，需要专家对事实进行调查、分析、研究。正确答案可能不止一个，应适当使用满意决策，避免寻求最优方案，陷入分析瘫痪，或决策成本溢出。
	
	* 复杂（Complex）
	
	绝大多数创新领域聚集在此，此特征为太多互相关反馈，因果关系不能提前预知，只能回溯。无法找到正确答案，只能有启示性的模式，解决方案已浮现的方式产生。需要创造一个能包容试错的决策环境。快速实验、重视迭代、反馈与响应。避免进行确定性计划造成行动失败。
	
	行动可以遵循基本规则，根据响应来调整行动。
	
	* 混沌（Chaotic）
	
	无法在系统级别确定因果关系，这个时候就需要管理者将混沌转换成复杂或简单。
	
	* 失序（Disorder）
	充满着噪音、无序。


	
	* 参考：
		GitChat·技术管理 | Cynefin 框架和不确定性管理思维
		Cynefin框架-百度百科

**Comment by RachyJ** [comment]
## 收获

* 深化了对「时空变形」的理解以及应用，包括时间、空间的变形，从认知角度，空间>时间。
   * 执行意图 未来->现在
   * 投资、保险 现在->未来
   * 做决策时，让过去的你，现在的你，以及未来的你一起发言，可以获得更全面的视角
   * 人在深海以及太空的感知与在地面的感知的不同
   * 营造合适的空间做创造性的活动，如咖啡馆、家里设置一个读书角等
   * 线上课程、电商也是一种时空变形
   * 科技的发展推进了一些时空变形，比如交通的发展促进了城市边界的扩张，从前慢 -》如今的快节奏

* 把一本书放在一个学科发展的大框架下看，阅读时可以结合不同的视角，比如作者的视角、自己的视角、其他人的书评，深化理解

* 写读书笔记，更多应该是「创造」，是「智识的生产」，而非摘抄。可以从最小行动-写卡片开始。

* 一天读同主题的几本书，有利于思维碰撞，深入对主题的理解

* 关键词：「自我终身教育」   「TRIZ」：Theory of Inventive Problem Solving

## To do

* 主题阅读+卡片输出

**Comment by emmawdm** [comment]
### Cynefin framework
- 术语：Cynefin framework
- 印象：
是一个概念性框架用于帮助决策。由Dave Snowden于1999年在IBM全球服务部工作时创建。

Cynefin（发音为kun-ev'in）是威尔士语，更具诗意的定义来自Kyffin Williams的一系列绘画作品的介绍，他是一位独特的威尔士艺术家，他使用油画创造了对他的故乡山脉的新认识以及他们与人民灵性的关系：“它描述这种关系：你的出生地和你的成长经历，你生活的环境以及你自然适应的环境。“ 

Cynefin模型的目的是通过提高边界意识和通过边界过渡触发决策，领导不同模式来实现意义提升。它强烈反对单一或理想化的模型，而是将多样性作为适应性的关键。

Cynefin提供五种决策，帮助管理人员确定他们是如何看待的情况，并感受自己和其他的行为。该框架借鉴了系统理论，复杂性理论，网络理论和学习理论。
  ![Cynefin framework](http://upload.hbrchina.org/2016/0926/1474860206372.jpg) 

 - 简单——当因果关系显然而见时，是简单的情况（simple），处理手法为"感受－归类－反应" （Sense-Categorise-Respond）
  - 复合——当需要专家作出分析的情况（complicated），处理手法为"感受－分析－反应"　（Sense-Analyze-Respond）
  - 复杂——如果因果关系只能从检讨中反映出来（complex），处理手法是"试探－感受－反应"　（Probe-Sense-Respond）  
  - 混沌——完全没有任何因果关系的混乱情况（chaotic），需要的是"行动－感受－反应"　（Act-Sense-Respond）
   
  - 如果连是属于以上哪个情况都不清楚的，这是一个无序的状态（disorder），等待参与者把情况安稳至上面四个其中之一的情况。

- 例子
   - 简单情景：最佳实践领域
   大家都知道的有步骤的标准化行为。
   
   - 复合情景：专家的领域
   例如车子坏了，汽车司机也许知道自己的车出了毛病，原因是发动机发出哐啷哐啷的响声，但要判断出了什么问题，司机就得把车开到修车行那里。
   
   - 复杂情景：规律自行浮现领域
   
   以YT为例，该网站的两位创始人不可能预见到如今存在的所有流媒体视频技术应用。然而，只要人们开始创造性地使用YOUTUBE，他们的公司就可以支持并扩充新出现的使用模式。举例来说，YOUTUBE已经成为一个受众广泛、表达政治观点的平台。它发起了关于总统候选人的辩论，而辩论素材就是人们上传的视频。

 - 混乱情景：快速响应领域
   
   2001年的“9.11事件”就属于这个类别。

 - 综合的例子
 
 在1993年的帕拉丁谋杀案中，副警长加希尔要同时面对4种情景。他必须通过媒体立即采取行动，以防最初的恐慌掀起波澜，具体做法是：让社区一直能了解到情况（混乱情景）；让警察局保持日常运作并遵循既定程序（简单情景）；请来专家（复合情景）；在危机之后的几天乃至几周时间里，安抚社区民众（复杂情景）。实际情况表明，最后一种情景难度最大。

 家长不敢让子女去上学，上班族担心工作场所的安全性。如果加希尔把这种局面误判为简单情景，他也许只会说：“坚持一下。”然而，这样做绝不会让社区民众放心；如果他把这种局面误判为复合情景，他会请专家证实安全程度，然而这会让他失去民众的信任。最终，加希尔为企业、学生、教师和家长建立了一个论坛，让他们表达自己的顾虑，并了解事实。这是针对复杂情景的正确方法——他让解决方案从社区中自行浮现，而不是设法将解决方案强加给社区。
  ![Cynefin framework](http://www.uml.org.cn/SoftWareProcess/images/2017060910.png)
  
- 出处
    - [Cynefin_framework-wiki](https://en.wikipedia.org/wiki/Cynefin_framework#cite_ref-Snowden1999_2-0)
   - [报告领导，你这辈子需要做的所有决定，只需一个框架搞定](http://www.hbrchina.org/2016-09-26/4541.html)
   - [The new dynamics of strategy: Sense-making in a complex and complicated world](http://alumni.media.mit.edu/~brooks/storybiz/kurtz.pdf)
   - [Cynefin组织复杂性中心 ](https://web.archive.org/web/20020614001545/http://www-1.ibm.com/services/cynefin/)
   - [Cynefin Framework Introduction](https://www.youtube.com/watch?v=N7oz366X0-8)
![cynefin](media/15388781084547/cynefin.jpg)


### 思考：
 > Williams和Hummelbrunner（2010）：“...... Cynefin确定了一种情况可以表现出来的四种行为：简单，复杂，复杂和混乱。这个术语并不新鲜;系统文献已经使用了几十年。但是， Cynefin支撑这四种状态的行为和属性并非完全来自系统理论甚至是混沌和复杂性理论.**Cynefin在很大程度上依赖于网络理论，学习理论和第三代知识管理。**
“至关重要的是，与许多网络和公司方法相比，Cynefin还采取了**认识论和本体论**的立场。类似于**软系统和关键系统的传统...... Cynefin探索了人们如何从情境中感知和学习**。” 

“至关重要的是，与许多网络和公司方法相比，Cynefin还采取了**认识论和本体论**的立场。类似于**软系统和关键系统的传统...... Cynefin探索了人们如何从情境中感知和学习**。” 对这句话暂时理解不了

阳老师说：
> 有四种场景，简单、复合、复杂、混乱
简单侧重分类；复合侧重分析、参数比较
这两类是专家导向的决策行为
但创业者、一流产品经理、优秀ceo不是干这两个事情的他们更多是应对复杂与混乱场景
**复杂场景侧重设立最小团队、最小规则、划定边界，让成果与伟大自然浮现**
**混乱场景侧重的是行动、更类似克莱因说的自然决策，比如他书中的消防员救火的决策行为**
个人学习、组织学习，其实都是超级复杂系统，越功利主义的学，其实会错过很多。**所以，此时，咱们要采取复杂决策、混乱决策，更多靠行动、边界设定，期待结果自然涌现。**

对如何进行行动和边界的设定暂时没有什么思路

**Comment by heshenxian1** [comment]
# heshenxian1的复盘

### 让你下次再来的三点收获或体验

- 多视角看一个问题

大家有不同的从业经历和工作背景，彼此提供不一样的信息和表达问题的方法，能让我看待一个主题和具体问题更为开放和多元。

- 术语的讲解弥清

个人身上容易中了知识诅咒而不知，在问答对话中学习着说人话，而减少使用各种术语行话。在分享输出中加深自己对一个术语概念的理解，更会举例子和接地气。

- 与开智书友的情感联结和信任

大家相互抛出自己的困惑和不解，用群智来提供解决办法之余，还有同侪的鼓励支持。



### 开智沙龙的三点改进建议

- 主持节奏改善

第一次组织主持线下沙龙，时间进度由原定三个小时变成了6个小时的对谈马拉松。

- 信息复盘更细致

沙龙分享信息复盘，不仅在议程最后总结，还需要在每个议题结束时，以及每一轮发言完毕甚至每一位同学讲完后，及时提取信息点，复述或小结。

- 沙龙形式更多样

本次主要是圆桌会议对谈讨论，以后可以形式更多，比如一两个人分享然后再主题讨论，比如主题讨论+聚餐，甚至还可以进行工作坊活动。



## 组织者和主持人视角小结



### 活动亮点

#### 沙龙议题明确

\-  开场「你与开智正典」

\-  主题「时空变形」

\-  终章「你眼中的开智沙龙」



暖场部分有三句话自我介绍，3min 简单说说你读过的开智正典。让参与者快速熟悉并相互了解一点读书。然后再开始下一轮的细说读开智正典的感受和困惑。

主题部分选题「时空变形」好，终章复盘活动收获同时，让同学们展望沙龙的组织和个人期待。



#### 中场点餐

时间安排上有中间点餐吃饭或者茶歇时间，给参与者休息时间和补充能量很重要。

持续深入沟通是一个很耗能量的过程，有充足食物和水，对于交流续航很重要。



#### 开智格调

每次活动对谈分享，都有足够信息密度，讨论后会涌现一些新知识新理解新行动新价值。

这一次活动不仅是线下读书会的启动，更有「心智镜头」，「分享如播种」等隐喻涌现，还收集整理不少「时空变形」的生活案例。

比如我自己，厘清掌握「时空变形」技法，需要认识「时空原型」，先标定了常见模式，基线、零点、主流、标准所在，然后才能有对时空模式的大胆变形，偏离零度来创造新感觉新行动新模式。事实性知识比想象力更重要。创新，需要对已有积累和资源的洞察。



#### 活动记录

感谢黎黎摄影拍照，记录沙龙的点滴。

书友们也有记录和复盘的好习惯，给活动留下思考的印迹。

讨论分享过程中或结束后，彼此在微信群和 github issue上及时增补一些背景知识和文章链接，让沙龙的信息沉淀消化更好。



### 活动改进点



#### 原则正确

**品味有三维度：信息，信任价值。**

开智沙龙持续发展为大家撑起一片学习空间，那沙龙活动本身需要不断创造更多信息、信任和价值。而好的开智沙龙，需要在信息、信任和价值上取得平衡。



开智沙龙组织者需要了解参与者的需求与期望。开智活动的体验很重要。好体验，多花点钱也是值得的。



开智沙龙更好的形式，是「既定环节 + 弹性时间」，是「必谈+ 选谈」。除了圆桌会议，除了主题分享和讨论，还可以多一些实验性活动开展内容探索，比如工作坊或故事会等。希望以后的开智沙龙可以开胃开心开智。



开智活动组织，群友可以主动发起和分工，组织者、主持人、分享者等角色可以交由不同人合作。



#### 细节正确

- 我若再做主持，需要做好场控，把控时间节奏和讨论议题主线。当发言者言毕，及时提取信息点复述小结或者以问题引导大家思考和参与进一步讨论。不同的时间切片中做好信息复盘和阶段小结，引导注意力回到议题主题上。
- 若做组织者，可以更提前公布活动主题和核心话题，以及一些背景知识材料准备和分享。比如这一次「时空变形」主题讨论，有了可讨论的issue沉淀资料，才更好激发大家讨论和思考，言之有物避免冷场或空谈。
- 若作为分享者，内容输出者，要注意调整信息密度，不宜太干太浓，多点举例子具体分析，提供事实证据比观念观点更有价值。分享有提前准备，有Plan B 是更好的。比如我提前带上iPad和电脑以及参考书，丰富了可用的分享媒介和素材。
- 若作为沙龙的发起者，把组织工作分得细一点让更多人参与进来，有人拍照有人文字记录有人主持，让参与的每个人惜力惜时中又有参与感。
- 空间先行，环境很重要。圆桌讨论就不要选桌子特长的地方；想激发大家的开放思维，可以选择天花板更高，灯光暖色调等空间。
- 先暖场，让大家放松再进入话题。议题开展和面对面沟通，先同步再引导。情感的同步，共识的同步，比如信息的确认，表达的复述。
- 注重好体验，线下活动强调具身认知，准备好食物和水之余，环境安静排除干扰，让每个参与者都有发言表达的机会。肢体语言的运用，声调的抑扬升降节奏，表情神态这些是线上活动所缺失的丰富信息，可在线下活动中多体验多表达。

**Comment by heshenxian1** [comment]
**在此附录阳志平老师的一篇写好备忘录的文章之要点**

> **信息点是写作的关键的关键。**

通过比较，我们清晰地意识到了，好的备忘录是什么？好的备忘录不是什么？
好的备忘录是什么：
1）是与同事、第三方沟通的记录，以备事后复盘；
2）是对未来即将开展的工作的提前预判与整体统筹；
3）是对相关同事的提醒；
4）是用逻辑说服对方。

坏的备忘录则是：
1）Word形式写的合同格式的文件；
2）感想与心得记录；
3）单方记录自己方的感受，而忘记记录参会嘉宾、与会者等。

简而言之，好的备忘录是帮助我们与同事、第三方建立共识。而坏的备忘录更多沉醉在自己世界中，谈感想，同时对敏感问题没有铺垫，没有考虑到看备忘录的不同身份的人的不同导致敏感问题的视角不同。

好备忘录的基本结构。
* 标题
* 摘要
* 信息点
* 行动点
* 疑问点

我们可以用上述的英文来描述好的备忘录的信息结构。title、abstract、info、Action、question。简称为：T-AIAQ结构。

摘要
一般来说，摘要包括：
* 人：有哪些人参加了？
* 地点：这个会在哪举办的？
* 摘要：接下来的备忘录，你的二级标题与要呈现的信息要点是如何的？

### 信息点
再接着说说主体。信息点：这个备忘录的文档update了什么信息；新增了什么信息？在信息点这里，是写备忘录的关键中的关键。

### 行动点

剩余的行动点则非常好写了。一般不要将行动点放在备忘录的正文中，更不要混入到信息点中。而是统一放到文章末尾。每一条行动点尽量只涉及到一个人、一件事情。这样更清晰。同时在行动点中指明相关提供支持的人、交付时间。

### 疑问点

疑问点则是没有达成共识的地方、有待确认的地方。
「疑问点」不是拿来写举手之劳，可以核实清晰的数据，而是写一些有待决策、有待商量的事情。
