### ISSUE TITLE
学习| 02Season「越读书单」领取 

### ISSUE THREAD

**Issue by heshenxian1** [heshenxian1/OpenMindClass#19]
## 学习 |「开智越读会」第2季主题阅读

《论语》学而篇，开宗明义谈学习之道。

学而篇微言大义，道出学习三条路径：

「学而时习之」一句，「三人行，择善而从」一句，「见贤思齐」一句。

学习与行动，学习与参照，学习与省思。

马奇老爷子《经验的疆界》一书，浓缩其人生智慧，处处有金句，亦说出学习三层次，学习系统巨复杂。

**量子力学的奠基人海森伯格曾说过，科学的本质是对话。**

市集的出现，城市的生长，乃至一家咖啡馆见面，它们都创造一个让人人对话的空间场所，于是交易得以进行，文化得以繁衍，思想得以交汇 。语言的棘轮，文明的传播，都离不开「对话」。

开智书友也曾寄语：从某种意义上，学习就是一场「对话」

> 从书本里学习，我们阅读的是前人的思想和智慧，是和前辈们「对话」；
>
> 从课程学习，我们是与传授新知的老师「对话」；
>
> 从身边人学习，我们就是与同侪「对话」。
>
> 后两种对话，不仅仅指人类交流时，语言所承载的信息，也指处于同一时空下，环境中存留着的人类记忆。

这一季，我们借着「学习」的主题学习，在开智这个容器中，生发一些不一样的对话。

#### 买书需趁早| 书单发布：

- 第一周：[为什么学生不喜欢上学? (豆瓣)](https://book.douban.com/subject/4864832/)
- 第二周：[经验的疆界 (豆瓣)](https://book.douban.com/subject/6687032/)
- 第三周：[创造知识的企业 (豆瓣)](https://book.douban.com/subject/1811450/)

#### 备选搭配书目：

- [超负荷的大脑 (豆瓣)](https://book.douban.com/subject/6758932/)
- [脑的阅读 (豆瓣)](https://book.douban.com/subject/6510682/)
- [智识的生产技术 (豆瓣)](https://book.douban.com/subject/26786537/)

- [Desirable difficulty|RBjork - Wikipedia](https://en.wikipedia.org/wiki/Desirable_difficulty)
- [RBjork_inpress.pdf](https://bjorklab.psych.ucla.edu/wp-content/uploads/sites/13/2016/07/RBjork_inpress.pdf)
- [如何学习 (豆瓣)](https://book.douban.com/subject/27081766/)

- [知识创造的螺旋 (豆瓣)](https://book.douban.com/subject/1734687/)
- [创新的本质 (豆瓣)](https://book.douban.com/subject/1837431/)

### 书单小事

关于「书单以及书单购买」的事情，注意看向这里：

- 书单里的书是要自行购买吗？

  答：是的

- 实在买不到怎么办？

  答：可以在网上寻找一章精读。或图书馆借阅

- 买书的时候，版本有讲究吗？

  答：选书逻辑，有最新版选择最新版，不必过多拘泥于版本，以及不鼓励大家去购买盗版啦。

**Comment by heshenxian1** [comment]
### 学习三书导读

你和我，回到学习的认知原理，知识创造的高阶模型中，回到心智与文化的底层里去重新理解学习。



> 推荐《为什么孩子不喜欢上学》《经验的疆界》《创造知识的企业》
>
> 分别对应学习方法、学习型组织主题，一本绝版的它们，胜过同类绝大多数的书籍。
>
> 一本绝版的《为什么孩子不喜欢上学》可以秒杀绝大多数谈学习方法的书。
>
> 一本绝版的《经验的疆界》可以秒杀99%的学习型组织图书。
>
> 一本绝版的《创造知识的企业》可以秒杀所有的知识管理图书。
>
> —— 阳志平点评荐书



**认知科学，终身学习者的秘密武器。**

《为什么学生不喜欢上学?》一书，是美国弗吉尼亚大学心理学教授威林厄姆的重要著作，是一本深受学生和教师欢迎的教育心理学著作。他用认知心理学的原理，详细分析了学生学习的过程和教师在课堂教学中必须注意的一些问题。

此书有九大认知原理，也是反常识。了解大脑认知规律，更好地改善学习习惯和教学沟通方式。



《经验的疆界》马奇这本留给后生晚辈的智慧之书，字字有珠玑，句句有出处。

从个人学习到组织学习，从模型故事行动这些高阶知识，去接近真实的世界。

在学习这一季主题阅读中，不妨采用抽样阅读法，结合个人志趣，专门抽读「学习」相关的章节段落，输出卡片。



我们阅读思考学习的时候，不要忘了这个逻辑链条—— 读书，是帮助自己理解世界，理解世界，是帮助自己留下作品。



《创造知识的企业》一书，野中郁次郎给你我提供了学习的高阶模型——SECI的知识螺旋。

我们借着此书，从个人学习走向组织学习乃至于社会化学习，有靠谱的知识创造模型可依。

生成大于管理，知识创造大于知识输入。

在信息时代智能时代，你我都是知识管理者，智识生产者，接过智者的利器，赋能自己的知识创造体系。

**Comment by heshenxian1** [comment]
### 学习的最小全局认识-补充导读



拓展阅读三篇，可对学习形成一个更好的最小全局认识：

#### 阳志平的元学习方法论

- [智力革命，欢迎你，聪明的学习者](https://mp.weixin.qq.com/s/TMjSqd6YVBy5ptyRlvSGoA)

长文阐述重点，它**从一种智力、两条路径、三种智力和智力革命**来阐释：  

- 何为聪明的学习者？
- 如何成为聪明的学习者？ 
- 如何辨别聪明的学习者？ 
- 如何进行智力革命？



- [工作谈020：元认知学习法（5）](https://mp.weixin.qq.com/s/nzzGl5cy4HRiUG87fAICuQ)

学习，是为改变行动。而行动改变的底层是心智习惯的改变。

元学习，是学习的学习。元学习三分，是主题学习，深度学习，行动学习。

元学习真正的底层突破是什么呢？**必要难度理论。**



#### 00 的向聪明人学习

- [重启学习系统，做个知识炼金术士](https://mp.weixin.qq.com/s/Bqd95DIQ8qlVf24G_lVGKA)

学习是怎么一回事？

> 以改变为目标，才是真正的学习。

发现和提出问题比解答问题更重要

主动深度加工比信息量更重要

刻意练习比记忆时长更重要

最终，融合、拓展和应用，才是真正意义上的“知识炼金术”。

**Comment by jianghangbei2016** [comment]
### 补充几篇文章：
* [古典教育与未来教育 - 阳志平的网志](https://www.yangzhiping.com/psy/Classical-education-and-Future-education.html)

* [阳志平：给自己的教育](https://mp.weixin.qq.com/s?src=11&timestamp=1544179689&ver=1283&signature=vjsceehy2rzHYw5TPL-9wk7PeL2r13CtU9oDNdw18kpBcTPvX5Nu-4Fsm2iXvhdnspBBAkXdhQ6aLNRzIkWg6kp8NRPI6AbKpUvc21OW7FY6thvj17okreBbmma9HS5b&new=1)

* [阳志平：如何进行主题学习？](https://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=2651929655&idx=1&sn=25aa8e498a0ed8b86c2242d6ef0d2c94&chksm=8bcf7a2fbcb8f339ba89454c6ba7a47956ce9b2ab64a97d100b6551fef291ae8279716426d37#rd)

* [阳志平：学习六律与六思](https://mp.weixin.qq.com/s?src=3&timestamp=1544178957&ver=1&signature=NJLBPm8J85d3h63ZFTAfyVVp4BskNaiZrgNPbhsWxG9228upR3ExH8qCowQpYEQ8Djj-liRvvQUxSv6J2yngOXkj0crK-7*TIe*ZGLAHZ7HhpjtdfGARyMm4wIJbC6ct4r-htj6hQUB0WiwyyPBAkU72Rozvxlr*A0QUb-pXI5k=)

* [阳志平：跨年答疑（1）— 学习十二问](https://mp.weixin.qq.com/s?src=3&timestamp=1544179086&ver=1&signature=k295MrkffWcA6hqb1*wCuOr*zW4f6ZQ-2DSEIX5U3BE9I3pA8yO2ilbO25iZzQYghej7EjYB-gIkOnjg2Si2mROFU3YCq53v3XVGbRdqy0gE0vSaPHlSqf7jjxVH*kNa-bg5ijXKOlA6TqTZqWDB70lI4xIrYh9Ucg3SqoTFiEM=)

* [阳志平：元学习——以微表情和网络心理学为例](https://mp.weixin.qq.com/s?src=3&timestamp=1544179086&ver=1&signature=NJLBPm8J85d3h63ZFTAfyVVp4BskNaiZrgNPbhsWxG*QZz3t3-UR7pqMjmS5x7-IVLqdKqvB51EFxbEdkZ0HAQPGP68JKzGeD3MCcMuWwm5gkuIxSitbIPIuvsBJl6UoPnoiPENeKIjUmeWwChMhs8IIn5a7uHlM6d7d-UcbxnQ=)

* [阳志平：七月夜谈](https://mp.weixin.qq.com/s?src=11&timestamp=1544179086&ver=1283&signature=vjsceehy2rzHYw5TPL-9wk7PeL2r13CtU9oDNdw18kr8zSfSTGuGigKlp9QTueEXsy9c0wW4QUyzVaY8N9NyFdDuCzZHhyIluIIerVNF-Gukw3BYAIcbynOeN5qJK*Hx&new=1)

* [阳志平：如何建立好的学习习惯系统？](https://mp.weixin.qq.com/s?src=3&timestamp=1544179086&ver=1&signature=k295MrkffWcA6hqb1*wCuOr*zW4f6ZQ-2DSEIX5U3BHVxxL*Qx9IrmdAsfn6-mUg3c6G6R1WoL5-OS8WbgVL0laFylMGLwEn8zFk2-gooHQ-UuuoOrWbP3oKjflgGcEFoybVXdKvZP5otsxmpHhCRGM-epCdk0Tely6CM9K-G8I=)

* [心智七问：如何成为内在动机驱使的人？](https://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=2651928764&idx=1&sn=4e8411f724077dd73c17cc8fc1b21b32#rd)




* [V型学习法](https://mp.weixin.qq.com/s?src=11&timestamp=1544178793&ver=1283&signature=pu3c0mmjbXcvlQXGwGxm9mG6qCNMa-SPqTKEMh-KqCoH1B1IHiplUJ3LstTva*fDAoSlIX6eT**rg3yP237k89cJVWAmWYnQlIwkLnpQ-g1lCpJYprdnGxlq5GlmnWV0&new=1)

* [Oliver Ding：高质量的分享驱动有效的学习 | 开智专栏](https://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=400336127&idx=1&sn=cd0a9607a4bb1b795c97760ca191fb1d)

* [Oliver Ding：善用学习部落，助益个人成长](https://mp.weixin.qq.com/s?src=3&timestamp=1544178310&ver=1&signature=NJLBPm8J85d3h63ZFTAfyVVp4BskNaiZrgNPbhsWxG9W6sTwBX7go9rhD47SCSvX80Yj7V0u2C6*Toen3LM3vDy9q9uPB0rCbN0FO-ZLaYSgZy6-9mHYqNM4Xoy2SMqpQJ8I5jUVPcV7CfL3eCyTQSfy7YPSNd4pjx07qAYECuc=)

* [Oliver Ding：4 条理由总结你为何要加入学习部落](https://mp.weixin.qq.com/s?src=3&timestamp=1544178310&ver=1&signature=NJLBPm8J85d3h63ZFTAfyVVp4BskNaiZrgNPbhsWxG9228upR3ExH8qCowQpYEQ8fhVGL45N8aIEz0q6vnV8Wxjr6Lwi33-Pwxv7vZYCrcMbKpGoT2EjuGEW8t5Br42PJBUattnbf4y83P6hUXZmzv7PBpkeROhy24RxcZmfmVE=)

* [Oliver Ding：6 个小建议助你打造更好的学习部落](https://mp.weixin.qq.com/s?src=3&timestamp=1544178310&ver=1&signature=NJLBPm8J85d3h63ZFTAfyVVp4BskNaiZrgNPbhsWxG9228upR3ExH8qCowQpYEQ8w7BUgLiOOSphQkUcXr0Mcbtm3ZkAojrKB7BdmzzpCpafgMFlE-64pUKhwAYSK27JgN3fGZl6dHmtk-16k3llAUEzKGtUi6rvWG67Nvuc39U=)

* [如何优化你的学习方法？](https://mp.weixin.qq.com/s?src=11&timestamp=1544179937&ver=1283&signature=vjsceehy2rzHYw5TPL-9wk7PeL2r13CtU9oDNdw18kpyOeW6CaJtQNsmUXSW094vehgSBUqoA-JkvhedHudlBS1EMIAI39-oWJnMWZK1wQ4AA3wUyRZCqaNY6lGw1kce&new=1)

* [如何做一个高阶学习者？](https://mp.weixin.qq.com/s?src=11&timestamp=1544179962&ver=1283&signature=vjsceehy2rzHYw5TPL-9wk7PeL2r13CtU9oDNdw18kpsNUhQABnagfXyWGH0AEK8lCx58bITBVfQSc2TK4GBh-DJVYkQvfO2HT-p3b0WgJdYSQ8MqQA4eb3HloSt*oiZ&new=1)

* [快速学习的终极指南](https://mp.weixin.qq.com/s?src=3&timestamp=1544180206&ver=1&signature=NJLBPm8J85d3h63ZFTAfyVVp4BskNaiZrgNPbhsWxG-dk4plON60IEwpSe*lyMzzBr3mhCoq-qp-LROtjx5NljMo0NuFGhRGZDQ*ouiEgUrfqlJFH45YJGNLg4UeFAa3kv7TF36x9A8PZg4smYX4HQ==)
