### ISSUE TITLE
【制度建设】如何促进积极投入？

### ISSUE THREAD

**Issue by absir1949** [heshenxian1/OpenMindClass#2]
读书难，投入难，如何让大家持续投入？从制度建设上我们可以做什么？

下面是一些思考，请大家批评、指正、补充。

1. 以月为单位，一个月为一次挑战。将年、季度拆分成月，减少启动和恢复阻力，促进最小行动。

2. 报名需收费，金钱倒逼投入一定程度很有效的，完成挑战后金钱退回，完不成挑战会扣除相应费用。剩余资金如何使用待定。

3. 如2余有经费，每季度奖励持续阅读者，以赠书方式。

4. 有退出机制，持续N个月未参加/未完成挑战，退出书友会，半年后才可以再次加入。

5. 进入有门槛，前期严格，需要参加过开智课程。

**Comment by heshenxian1** [comment]
制度建设和组织规则设置，需要考虑回归到读书会的初衷或者目标上，然后兼顾流程设计尽可能自动化，减少人力操作。看怎么样能最小成本而大时间周期持续。

> 人品守恒，做事兼顾动机、过程，结果。滋养内在动机，过程注重参与，结果交付价值。


@absir1949 
1. 有想过以月为单位，但考虑到读书本身是大周期的事，开智部落曾经的读书月度安排挺紧张的，当月有事很容易节奏跟不上。季度主题没问题，月度设置挑战可考虑，怎么做能增加读书看得见的反馈？

2. 前期暂时不设置收费机制，可以参考线上读书会是开智校友的一项福利设计，参加过开智课程可以作为筛选条件，第五点解决。活动经费需要有的，可以是开智校友会的杭州分部运营。季度奖励和金钱倒逼可以换种形式开展，比如以三个月一主题为单元，一季度开始前就交付一笔钱到经费池中，相当于提前预约报名参加季度线下活动，报名者到时候参与线下活动免费，未能完成主题阅读未能参与线下活动的也不退款，奖励有赠书等方式。

3. 尽量减少组织者和参与者与开智阅读不相关的其他工作量。开智总部有现成套用模式稍作修改可迁移为佳。铁打的营盘流水的兵，开智部落之前有什么好的运维经验和正确细节能迁移过来用，这一点用好会省力。

4. 比起退出机制，我更关注有哪些点能作为书友会的里程碑节点，有什么设计能促进彼此的交流和反馈，促进输出和分享。
