### ISSUE TITLE
《为什么学生不喜欢上学?》|01W 开智精读公告 

### ISSUE THREAD

**Issue by heshenxian1** [heshenxian1/OpenMindClass#20]
为什么学生不喜欢上学?

Hi~ 开智的小伙伴

开智正典阅读 第二季主题为「学习」。在12月、1月、2月的第 1 周，咱们一起阅读 [为什么学生不喜欢上学? (豆瓣)](https://book.douban.com/subject/4864832/)

可搭配如下选读：
* [超负荷的大脑 (豆瓣)](https://book.douban.com/subject/6758932/)
* [脑的阅读 (豆瓣)](https://book.douban.com/subject/6510682/)
* [如何学习 (豆瓣)](https://book.douban.com/subject/27081766/)

请小伙伴儿在 在 01wd6（181208）23：42 前，将卡片笔记回复到本 Issue 下，读书卡片格式和示范详见  [卡片笔记撰写指南](https://github.com/OpenMindClub/OpenMindWorld/wiki/HbCard)。

## 提交格式

```
# 阅读章节名称
## 术语卡
## 人名卡
## 反常识卡
## 金句卡
## 行动卡
## 技巧卡
## 任意卡
```

## 注意

如果时间紧张，建议完成最小行动，优先选择撰写反常识卡、术语卡、人名卡，完成比完美更加重要！

不用贪多，每周选一章精读即可。

**「学习」主题导读请看** ：[学习| 02Season「越读书单」领取 · Issue #19 · heshenxian1/OpenMindClass](https://github.com/heshenxian1/OpenMindClass/issues/19)

**Comment by bravejiawen** [comment]
# 第一章 为什么学生不喜欢上学
## 人名卡
丹尼尔·T.威林厄姆（Daniel T. Willingham，1961- ），弗吉尼亚大学心理学教授，研究重点是将认知心理学和神经学应用于K12教育。认为大脑不是用来思考的。2009年发表《为什么学生不喜欢上学》。
出处：[Daniel T. Willingham - Wikipedia](https://en.wikipedia.org/wiki/Daniel_T._Willingham)

## 反常识卡
常识：人与动物的区别在于人类善于思考，而动物不会。
反常识：大脑不是用来思考的，大脑会回避思考。但当认知环境符合一定要求时，大脑会在好奇心的驱使下，喜欢上思考。
发现者：Daniel T. Willingham
发现记录：人生来就有好奇心，但我们不是天生的杰出思想者；除非认知环境符合一定的要求，否则我们会尽可能地避免思考。
出处：《为什么学生不喜欢上学》P1
例子：人们选择填字游戏而不愿意做代数题，博诺的自传比济慈的自传畅销。
启示：寻找保持好奇心的方法。创造引导思考的认知环境。

## 金句卡
> 好奇心与生俱来，但它很脆弱。
> 解决问题带来愉悦感.

**Comment by bravejiawen** [comment]
第二章 教师应如何教授学生所需的技巧
## 金句
> 我们希望学生能够进行批判性思考，并且逻辑缜密，而如果没有背景知识，这些都是不可能实现的。P30
> 事实上，人们利用记忆来解决问题的次数比你预期的要多的多。P31
> 我承认学习不会运用的知识没有什么价值，但是没有事实性知识，有效的思考也无法进行。P37

## 反常识卡
- 反常识：如果没有背景知识，我们无法进行有效的批判性思考。
- 启示：多读书

**Comment by jianghangbei2016** [comment]
# 《为什么学生不喜欢上学》第一章
## 反常识卡1
* 常识：人类擅长思考
* 反常识：人类不擅长思考，人的大脑不是用来思考的，而是用来避免思考的
* 发现者：丹尼尔•T•威林厄姆（Daniel T. Willingham)
* 发现记录：
  * 原文：大脑让你避免思考的两种方式。首先，一些最重要的功能（比如视觉和行动）不需要思考：你不需要思考你看到的事物就知道周围有什么。其次，你倾向于用记忆而不是思考指引行动。
  * 出处：《为什么学生不喜欢上学》2010，P.2-P.6
* 例子：开车，有了成功驾驶的记忆后，不需要思考
* 启示：思考能力需要刻意练习，否则日常生活都是靠记忆存活。

## 反常识卡2
* 常识：记忆储存的是事件和事实
* 反常识：记忆还储存指引行动的策略
* 发现者：丹尼尔•T•威林厄姆（Daniel T. Willingham)
* 发现记录：
  * 原文：在做大部分决定时， 我们不会停下来考虑可能的解决方法
  * 出处：《为什么学生不喜欢上学》2010，P.4
* 例子：开车回家在哪里转弯，找到去上班的路线
* 启示：遇到重要的事情不要立刻做决定，停下来认真思考

**Comment by chenmingio** [comment]
### 宝贵的好奇心

- 解决问题的过程能产生快感。直接告诉答案则没有这个效果。
- >我说过思考是缓慢的、费力的和不确定的。尽管如此，人们还是喜欢思考——更精确地说，我们知道解决这一问题能够带来愉悦感后才会喜欢思考。P9
- 好奇心感兴趣的问题，不能太难，也不能太容易。一个适中的问题是一个预测信号，预测有可能出现的奖励。

### 如何激发好奇心
- 让内容变得与学生“相关”，与他熟悉喜欢的事物联系起来
- 围绕一个线索（看似不可能的问题）展开调查

### 概念迁移与深层事实
- 理解的深层事实是用老知识来理解新知识，即再认。
- 举例子的作用就是帮助老知识与新知识对应起来。
- 检验理解的一种标准是会迁移概念
- 概念迁移的困难是无法想到深层现实
- 人无法注意到深层现实，因为…
    - 一件事情有很多种深层现实的可能
- 在不同领域练习知识应用有助于概念迁移

### 记忆与遗忘
- 记忆是思考的遗留物
    - 你想什么就记住什么，人只能注意事物的某一方面，其他视而不见的信息不会记住。那应该思考哪一方面呢？
    - 最好的关注点是意义
- 强烈情绪下的确能更好记住当下信息，但不适用于日常学习
- 重复也不一定有效，一定要入脑，也就是加工处理
    - 可以是运用知识制造实例
    - 可以是用自己的话解释新概念
- 运用故事是个好办法，把信息串联起来
    - 故事有因果
    - 写科普文也能用故事框架，而不是事实罗列
- 经常使用才不会遗忘
