### ISSUE TITLE
《经验的疆界》|02W 开智精读公告

### ISSUE THREAD

**Issue by heshenxian1** [heshenxian1/OpenMindClass#21]
Hi~ 开智的小伙伴

开智正典阅读 第二季主题为「学习」。在12月、1月、2月的第 3 周，咱们一起阅读：[经验的疆界 (豆瓣)](https://book.douban.com/subject/6687032/)

可搭配如下选读：

* [智识的生产技术 (豆瓣)](https://book.douban.com/subject/26786537/)
* [Desirable difficulty|RBjork - Wikipedia](https://en.wikipedia.org/wiki/Desirable_difficulty)
* [RBjork_inpress.pdf](https://bjorklab.psych.ucla.edu/wp-content/uploads/sites/13/2016/07/RBjork_inpress.pdf)

请小伙伴儿在 在 03wd6（181222）23：42 前，将卡片笔记回复到本 Issue 下，读书卡片格式和示范详见  [卡片笔记撰写指南](https://github.com/OpenMindClub/OpenMindWorld/wiki/HbCard)。

## 提交格式

```
# 阅读章节名称
## 术语卡
## 人名卡
## 反常识卡
## 金句卡
## 行动卡
## 技巧卡
## 任意卡
```

## 注意

如果时间紧张，建议完成最小行动，优先选择撰写反常识卡、术语卡、人名卡，完成比完美更加重要！

不用贪多，每周选一章精读即可。

**「学习」主题导读请看** ：[学习| 02Season「越读书单」领取 · Issue #19 · heshenxian1/OpenMindClass](https://github.com/heshenxian1/OpenMindClass/issues/19)

**Comment by bravejiawen** [comment]
# 第二章 通过复制成功而学习
## 人名卡
詹姆斯·马奇（James Gardner March ，1928.1.15-2018.9.27）美国社会学家，卡内基学派的核心成员，管理大师心目中的大师。涉猎范围极广，包括组织心理学、行为经济学、计算机仿真、统计学等等。最著名的是他对组织的研究，（与理查德·赛尔特一起）提出了企业和组织决策的行为理论。侧重于了解在个人、团体、组织、公司和社会的决策是如何发生的以及影响决策制定的因素。
[James G. March - Wikipedia](https://en.wikipedia.org/wiki/James_G._March)

## 反常识卡
- 常识：某项措施有效，可以复制使用，措施产生不太好的结果，就选择回避。这样通常能得到比较好的结果。
- 反常识：通过复制成功寻找最佳选项容易出现问题，会因为好用而容易忽略掉潜力最高的选项。
- 发现者：Barnett and Hansen,1996
- 发现记录：每次的潜在结果分布内源于历次所做选择和历次变现结果。这种内源性在有些案例表现为消耗：也就是因为复制本身对后续结果有害，所以，平均而言，复制成功导致绩效降低。最显而易见的案例涉及，资源因使用或竞争而消耗。其他案例涉及，优势因开发而丧失。
- 出处：《经验的疆界》P38
- 例子：“假设一位网球选手采取的策略是把球打到对手弱的一边（对手长于右手，就打到左边，对手长于左手，就打到右边）。这一策略会增加短期获胜的可能性，但是与此同时会为对手提供练习较弱那边的机会。随着时间的推移，练习效应会减小对手两手之间的能力差异，进而减弱“把球打到对手较弱一边”这个策略的竞争优势。”
- 启示：一味追求绩效不利于长远发展。多试用优点较多但可能由于不熟悉而导致效果不好的做法（流程、形式）。

## 反常识卡
- 常识：人们往往会不自觉地追求更高的收益，更小的损失及风险。
- 反常识：在收益面前规避风险，而在损失面前寻求风险。低估极稀有、极正面事件的发生可能性，进而无意识规避风险，使其不能发生（收益）；低估极稀有、及其负面事件的发生可能性，进而无意识寻求风险，使其发生（损失）。
- 发现者：Kahneman and Tversky,1979；March,等
- 发现记录：当期望值高于目标（收益），个体倾向于规避风险；当期望值低于目标（损失），个体倾向于寻求风险。
- 出处：《经验的疆界》P48
- 例子：重大科学突破。及其正面，但发生机会很小，学习者会无意识地规避风险，而降低高度敬业、积极投入的力度。而核电厂的核事故，后果十分严重但几率低，大多数操作员都不会经历，进而无意识寻求风险，复制增加核事故发生可能性的行为。
- 启示：“经验具有双面性，一方面让人泰然处之，一方面让人麻痹大意”，改变和自己的关系，去承担小小的风险，走出舒适区。

## 金句卡
> 智慧一般包括两个互相联系但有所不同的要素。一是，有效地适应环境。二是优雅地诠释经验。
> 复制成功的三种经典机制：试误、模仿、天择。

## 术语卡
- 术语：低智学习
- 印象：基础是复制成功，即在不理清因果结构的情况下复制和成功有关的行动。复制成功包括三种机制：试误、模仿、天择。试误即自我摸索、复制与成功相连的行动，回避与失败相连的行动，模仿即观察其他行动着的经验，天择即逐渐淘汰与失败相连的属性。
- 例子：在老虎机实验中，对结果的分布是未知的，逐一对选项进行尝试，结果会随着尝试时间的增加，取得最佳策略的概率增加。/ 东施效颦 / 在销售员销售过程中，绩效好的销售员的属性会被复制，如热情耐心等，不符合该行业业绩发展的属性会被淘汰，如高傲等。
- 出处：《经验的疆界》P23-44

## 行动卡
我生活中有哪些低智学习？
从复制成功的三个机制来看，我生活中的大部分事情都是低智学习。比如说育儿，能不能让孩子自己好好吃饭，选择的路径一是摸索方法，二是看看育儿达人怎么说，照着做，结果都不乐观。
