### ISSUE TITLE
《创造知识的企业 》|03W 开智精读公告

### ISSUE THREAD

**Issue by heshenxian1** [heshenxian1/OpenMindClass#22]
Hi~ 开智的小伙伴

开智正典阅读 第二季主题为「学习」。在12月、1月、2月的第 2 周，咱们一起阅读：[创造知识的企业 (豆瓣)](https://book.douban.com/subject/1811450/)

可搭配如下选读：

* [知识创造的螺旋 (豆瓣)](https://book.douban.com/subject/1734687/)
* [创新的本质 (豆瓣)](https://book.douban.com/subject/1837431/)

请小伙伴儿在 在 02wd6（181215）23：42 前，将卡片笔记回复到本 Issue 下，读书卡片格式和示范详见  [卡片笔记撰写指南](https://github.com/OpenMindClub/OpenMindWorld/wiki/HbCard)。

## 提交格式

```
# 阅读章节名称
## 术语卡
## 人名卡
## 反常识卡
## 金句卡
## 行动卡
## 技巧卡
## 任意卡
```

## 注意

如果时间紧张，建议完成最小行动，优先选择撰写反常识卡、术语卡、人名卡，完成比完美更加重要！

不用贪多，每周选一章精读即可。

**「学习」主题导读请看** ：[学习| 02Season「越读书单」领取 · Issue #19 · heshenxian1/OpenMindClass](https://github.com/heshenxian1/OpenMindClass/issues/19)

**Comment by RachyJ** [comment]
## 反常识卡

日本企业的成功源于其在「组织知识创造」方面的技能和专长，即企业作为一个整体，创造新知识、传播新知识以及将新知识体现在产品、服务和系统中的能力。组织知识创造是日本企业独特的创新方式，它们特别擅长持续地、渐进地、螺旋式地创新。（原来以为日本企业的成功在于其「匠人精神」）

出处： 《创造知识的企业》2006，p1

**Comment by RachyJ** [comment]
## 术语卡：形式知识

* 印象：可以用语言或数字表达，以”硬性“数据、科学方程式、计算机编码等形式进行交流和分享的相对正式、成体系的知识。
* 例子：各种书籍、手册、数字内容等

## 术语卡：暗默知识

* 印象：高度个人化，很难形式化，因此很难与别人交流或共享的知识。包含两个部分：1. 技术维度，各种非正式、难以准确描述的技能或技艺  2. 认知维度，包括心理图式、心智模式、信念和知觉等。

   形式知识只是冰山一角，很多暗默知识隐藏其下。

   暗默知识的启示：

   - 最有效的学习来自直接的经验，「试与误」，通过心+身体学习「具身认知」，孩子的学习方式
   - 对创新的思考--光把数据和信息放在一起无法引起创新，创新是高度个人化和组织自我更新的过程，需要对愿景和使命的认同，组织成员间的相互作用
   - 「纸上学来终觉浅，绝知此事要躬行」手册、书本、讲义上获得的形式知识很多浮于表面，无法真正发挥作用，需要更重视「暗默知识」，那些可以通过比喻、图画或体验来获得的高度主观的洞察力、直觉和预感。

* 例子：直觉、预感；工匠手艺；大师的手感；相信人性本善
* 出处：《创造知识的企业》2006，p7-11

**Comment by heshenxian1** [comment]
## 任意卡

内隐知识或暗默知识的认识论底层，是对客观主义的认识论之否定。

这里有一个反常识点——**人和知识不是分离的。或者说，知识，一定是与 人捆绑在一起的。**知识的传递和生发，离不开一个具体的「场」，这个场可以是咖啡吧，图书馆，一座城，一个车厢里，发生在两个鲜活个体间，一个开放对话的团体，或者是一个共同推进的项目中。



阳志平在安人书院中推荐杰作《个人知识》，能帮助我们更深刻理解知识与学习如何在个体与组织中生发迁移。



> 认知科学习惯将暗默知识（tacit knowledge）翻译为“内隐知识”。它来自英国哲学家波兰尼（Michael Polanyi）1958年的著作《个人知识》（Personal Knowledge）。之后，美国心理学家雷伯（A.S.Reber）在其基础上做了大量研究，于1967年在著作《人工语法的内隐学习》中正式提出了内隐学习理论。
>
>
>
> 这本书即波兰尼的经典之作。在此书中，他系统提出了自己的内隐知识观念。影响了之后认知科学的发展。另一本《认知与存在》，继续对自己的学说进行了完善。如波兰尼所言：
>
>
>
> > 自休谟与洛克以来，客观主义的认识论认为真正的知识必须经得起经验的检验，不得超越经验，如果知识与经验冲突，人们必须随时准备抛弃这种“知识”。依据这种认识论，我们必须尽力排除求知过程之中的个人系数，才能达至完全客观的理想该书认为，这种以主客观分离为基础的认识论不仅是错误的，而且还是有害的。事实上，求知是一种技能，是一种个人怀着责任感与普遍性意图、从启发性前兆不断趋近真实的过程，一旦缺少了个人的求知热情与参与，任何有意义的知识都无法获得。而个人对求知的寄托、科学社群对知识主张的共识，以及社会对自由思维的尊重，都是人类知识增长过程中环环相扣的要素。


- 参考出处：https://wx.zsxq.com/dweb/# 安人书院 荐书 Book024：个人知识

**Comment by RachyJ** [comment]
## 任意卡

![image](https://user-images.githubusercontent.com/12043650/50961801-aba03800-1503-11e9-8d44-c0c83e4d2464.png)


组织知识创造的过程：

1. 共同化 - 互动的「场」里，成员间相互分享彼此经历和心智模式，产生「共感知识」
2. 表出化 - 通过对话或集体反思，以比喻、类比的方式，产生「概念知识」
3. 联结化 - 新创造的知识与其他部门现有知识形成「网络」，产生「系统知识」，例如原型和新的组件技术
4. 内在化 - 知识体验在新产品、服务或管理上，产生「操作知识」
