### ISSUE TITLE
学习 | 02 Season | 整理阳老师谈学习的文章列表

### ISSUE THREAD

**Issue by huangyu9887** [heshenxian1/OpenMindClass#26]
### 缘起

> 我们这一个季度的主题是学习，有一个技巧可以用来实践——学习，site：yangzhiping.com 用阳老师的博客作为辅助材料主题学习。

### 主题

整理阳老师谈学习的文章列表，然后按个人学习；社会化学习来分类，或者其他更好的分类方式也行。

###  CHANGELOG

- 20181225

**Comment by bravejiawen** [comment]
- 尝试了百度site，发现没有Google那么全，google搜出来有240几条。打算批量打开然后批量markdown，不成功（被拒绝）。想做translators批量获取到zotero，还在研究中。。。
- 更一手的资源[Learning theory (education) - Wikipedia](https://en.wikipedia.org/wiki/Learning_theory_(education))

**Comment by bravejiawen** [comment]
先发在这里供参考，还没分类，不知道怎么分类。通过google site:yangzhiping.com 学习   获得，省去重复列表和看起来无关的条目。
* [我们为什么害怕学习？ - 阳志平的网志](https://www.yangzhiping.com/psy/why-do-not-students-like-school.html)
* [如何建立好的学习习惯系统？ - 阳志平的网志](https://www.yangzhiping.com/psy/EstablishLearningSystem.html)
* [如何提高学习效率 - 阳志平的网志](https://www.yangzhiping.com/column/improve-learning-efficiency.html)
* [学习的科学 - 阳志平的网志](https://www.yangzhiping.com/column/The-science-of-learning.html)
* [为什么多数人很难持续学习？ - 阳志平的网志](https://www.yangzhiping.com/column/keep-learning.html)
* [写给新读者的文章导航（2）：思维、学习与写作 - 阳志平的网志](https://www.yangzhiping.com/psy/guid2.html)
* [如何学习一门新的编程语言？——在学习区刻意练习 - 阳志平的网志](https://www.yangzhiping.com/tech/learn-program-psychology.html)
* [关于学习的学习 - 阳志平的网志](https://www.yangzhiping.com/column/cognitive-learning.html)
* [像专家那样学习 - 阳志平的网志](https://www.yangzhiping.com/column/effective-learning.html)
* [聪明的学习者 - 阳志平的网志](https://www.yangzhiping.com/psy/learn)
* [元认知学习示范：以TED为例 - 阳志平的网志](https://www.yangzhiping.com/psy/meta-learning.html)
* [不上大学，你可以学些什么？ - 阳志平的网志](https://www.yangzhiping.com/psy/open-classroom.html)
* [为什么多数人很难持续学习？ - 阳志平的网志](https://www.yangzhiping.com/column/keep-learning.html)
* [如何学习科学：开放科学工具箱 - 阳志平的网志](https://www.yangzhiping.com/psy/open-science-toolbox.html)
* [如何学习一门新的编程语言？——在学习区刻意练习 - 阳志平的网志](https://www.yangzhiping.com/tech/learn-program-psychology.html)
* [元认知学习法（1） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk001)
* [元认知学习法（6） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk006)
* [第五章：元认知学习法 - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/README)
* [聪明的学习者 - 阳志平的网志](https://www.yangzhiping.com/psy/learn)
* [元认知学习法（4） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk004)
* [行动学习 - 阳志平的网志](https://www.yangzhiping.com/column/action-learning.html)
* [为什么要趁年轻去做更难的事情 - 阳志平的网志](https://www.yangzhiping.com/column/tacit-knowledge.html)
* [互联网时代的学习 - 阳志平的网志](https://www.yangzhiping.com/column/internet-learning.html)
* [元认知学习法（2） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk002)
* [元学习——以微表情和网络心理学为例 - 阳志平的网志](https://www.yangzhiping.com/psy/yang.talk.html)
* [像黑客一样学习与写作 - 阳志平的网志](https://www.yangzhiping.com/tech/hacker-writer.html)
* [心智学徒计划答疑 - 阳志平的网志](https://www.yangzhiping.com/psy/MindsetTrainee.html)
* [聪明的学习者 - 阳志平的网志](https://www.yangzhiping.com/column/smart-learner.html)
* [如何高效利用GitHub - 阳志平的网志](https://www.yangzhiping.com/tech/github.html)
* [聪明的学习者 - 阳志平的网志](https://www.yangzhiping.com/psy/mind-SmartLearner.html)
* [高阶算命术 （下） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter2/talk003)
* [智商税 - 阳志平的网志](https://www.yangzhiping.com/psy/YangQ&A-RationalMind.html)
* [英才论（3） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter4/talk003)
* [如何重塑 “职业身份.” - 阳志平的网志](https://www.yangzhiping.com/column/reshape-professional-identity.html)
* [心智工具箱 - 阳志平的网志](https://www.yangzhiping.com/psy/mindtools)
* [R in Psychology学习目录 - 阳志平的网志](https://www.yangzhiping.com/tech/R-in-Psychology.html)
* [冷读热读 - 阳志平的网志](https://www.yangzhiping.com/psy/book)
* [如何成为内在动机驱使的人？ - 阳志平的网志](https://www.yangzhiping.com/psy/YangQ&A-SelfDetermination.html)
* [构建优雅的知识创造系统 - 阳志平的网志](https://www.yangzhiping.com/psy/yang-KnowledgeSystem.html)
* [如何21天写一本书（1） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/ps1/talk001)
* [Untitled](https://www.yangzhiping.com/files/pubs/smartlearner20130331.pdf)
* [如何21天写一本书（4） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/ps1/talk004)
* [如何21天写一本书（3） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/ps1/talk003)
* [成为自己，才是对自己的奖赏 - 阳志平的网志](https://www.yangzhiping.com/column/be-yourself.html)
* [超越“1万小时定律” - 阳志平的网志](https://www.yangzhiping.com/column/laws-of-ten-thousand-hours.html)
* [如何21天写一本书（2） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/ps1/talk002)
* [读书八字诀：怎样读得通透？ - 阳志平的网志](https://www.yangzhiping.com/column/reading-8tips.html)
* [看得见的未来不叫未来 - 阳志平的网志](https://www.yangzhiping.com/column/future-unpredictable.html)
* [如何写一篇“好”文 - 阳志平的网志](https://www.yangzhiping.com/psy/bad-essay.html)
* [跨年答疑（3）：卡片十二问 - 阳志平的网志](https://www.yangzhiping.com/psy/happy-new-year-faq3.html)
* [人生的STC算子 - 阳志平的网志](https://www.yangzhiping.com/psy/OMSalonSpeech.html)

CHANGELOG
- 20190104

**Comment by heshenxian1** [comment]
嗯，主题学习，分类分组块，然后就能更好分组块批量阅读。

**Comment by heshenxian1** [comment]
学习是一个巨复杂系统。学习之道充满各种看不见的风险和陷阱。柏拉图时代的智者，就提醒我们警惕那些兜售智者术的人。

面对今天的所谓知识付费的时代，我们不要忘了教育从来都很贵。信息爆炸的潮流里，爆炸的是垃圾信息，三四五手的信息，而一手信息，源头知识依旧稀缺。信息汪洋，源头大于碎片，有限大于无限。当你取得一瓢源头活水，智识甘泉的时候，不要忘记「知道了」并不等于「学会了」。大脑知晓了只是开端，知识之旅才刚起步，真正学会需要行动。行动中，实践里，把知识化为你身体的一部分，在你的生命中长出一棵知识树来。


楼上同学整理了阳志平博客中谈学习的系列文章。种种篇章，娓娓道来的淙淙知识密流中，我试着理出一条线，供自己供师友同侪，常读常新。


学习之道，与君同行。

> 一位冒险者踏上解救公主或击败恶龙的道路，最大的风险莫过于南辕北辙。
>
> 学习者的道路也存在类似风险。终其一生，学习者面临的陷阱与风险可能远远超过从事其他任何事情的人。
> ——阳志平


## 学习之道-文章十篇

### 路漫修远-一二三四

#### 一

学习的学习，最小阅读，学与思，知与行。

**善用记忆规律，谨记学习六律**

只读一篇文章，那就读**「学习的科学」。**

- [学习的科学 - 阳志平的网志](https://www.yangzhiping.com/column/The-science-of-learning.html)



#### 二

学习学习再学习，你应该知道元认知，了解大脑心智模式，若只读两篇，它们是：

> **“博观而约取，得鱼而忘筌”。**

- [关于学习的学习 - 阳志平的网志](https://www.yangzhiping.com/column/cognitive-learning.html)
- [如何提高学习的成功率 - 阳志平的网志](https://www.yangzhiping.com/column/Improve-the-success-rate-of-learning.html)



#### 三

全局三篇，引领方向。

做一个聪明的学习者，建立学习的最小全局认识，学习是生长，学习是创造。

- [聪明的学习者 - 阳志平的网志](https://www.yangzhiping.com/psy/mind-SmartLearner.html)
- [如何建立好的学习习惯系统？ - 阳志平的网志](https://www.yangzhiping.com/psy/EstablishLearningSystem.html)
- [构建优雅的知识创造系统 - 阳志平的网志](https://www.yangzhiping.com/psy/yang-KnowledgeSystem.html)


#### 四

自修之路，丰富学习资料，学习答疑，读四篇

- [不上大学，你可以学些什么？ - 阳志平的网志](https://www.yangzhiping.com/psy/open-classroom.html)
- [如何学习科学：开放科学工具箱 - 阳志平的网志](https://www.yangzhiping.com/psy/open-science-toolbox.html)
- [**给自己的教育** - 阳志平的网志](https://www.yangzhiping.com/psy/self-edu.html)
- [跨年答疑（1）：学习十二问 - 阳志平的网志](https://www.yangzhiping.com/psy/happy-new-year-faq1.html)


#### 元认知学习法

- [元认知学习法（1） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk001)
- [元认知学习法（2） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk002)
- [元认知学习法（3） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk003)
- [元认知学习法（4） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk004)
- [元认知学习法（5） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk005)
- [元认知学习法（6） - 阳志平的网志](https://www.yangzhiping.com/worksmarter/chapter5/talk006)
- [元认知学习示范：以TED为例 - 阳志平的网志](https://www.yangzhiping.com/psy/meta-learning.html)
- [元学习——以微表情和网络心理学为例 - 阳志平的网志](https://www.yangzhiping.com/psy/yang.talk.html)
