### ISSUE TITLE
学习 | 02 Season | 分类

### ISSUE THREAD

**Issue by huangyu9887** [heshenxian1/OpenMindClass#27]
### 缘起

小何教练一个感慨：

> 会分类，真的是超级底层的能力。

我脱手而出了一个时不常冒出的问题

> 现在有一个问题，怎么能提高分类的能力呢？这个我还挺欠缺的

过后，其实一想，这种问问题姿势不对，既不具体，也不本质，怎么可能期待有一个好解嘛？

> 你关于分类的认知雪球是啥样的？你对分类的最小全局认识如何，有啥高阶模型和实践策略？

### 探索

挖一个坑给自己，说不定问着问着自己就明白了。

### 参考

- [范畴（哲学概念）_百度](https://baike.baidu.com/item/%E8%8C%83%E7%95%B4/20395)
- [Category Theory_Wiki](https://en.wikipedia.org/wiki/Category_theory)

# Changelog

- 20190109 init

**Comment by heshenxian1** [comment]
分类学，编目学，文献学，目录学，都是信息分析的古代版。
编目，也是帮助我们内隐分类的底层能力的训练。

bibliography ==》书目学，目录学
Taxonomy  ==》 分类法，分类学

> 编目：按照一定的标准和规则，对某范围内文献信息资源每种实体（Item）的外部特征和内容特征进行分析、选择、描述，并予以记录成为款目，继而将款目按一定顺序组织成为目录（Catalogue）或书目（Bibliography）的过程。


了解多点数据库原理，分类学规律，以及相关系列分类的最小全局认识，学会更好地分类，比如多用Zotero，比如多知道不同学科领域的分类树，如生物学的分类等等。

**Comment by heshenxian1** [comment]
> 分类学 taxonomy，systematics
> 分类学是区分事物类别的学科。
> 英文分类学taxonomy指动植物分类， systematics指系统分类。
> “分”即鉴定、描述和命名，“类”即归类，按一定秩序排列类群，也是系统演化。
> 广义分类学观点：分类学就是系统学。指分门别类的科学。
> 


## 相关概念
[文献编目_百度百科](https://baike.baidu.com/item/%E6%96%87%E7%8C%AE%E7%BC%96%E7%9B%AE)
[分类学_百度百科](https://baike.baidu.com/item/%E5%88%86%E7%B1%BB%E5%AD%A6)
[自然科学（科学三大领域之一）_百度百科](https://baike.baidu.com/item/%E8%87%AA%E7%84%B6%E7%A7%91%E5%AD%A6/260539)

## 分类体系案例
[学科分类与代码](http://dean.pku.edu.cn/urtpku/yjxk.html)
[生物分类_百度百科](https://baike.baidu.com/item/%E7%94%9F%E7%89%A9%E5%88%86%E7%B1%BB)
[Home - Taxonomy - NCBI](https://www.ncbi.nlm.nih.gov/taxonomy)


> 生物分类学是研究生物分类的方法和原理的生物学分支。
> 分类就是遵循分类学原理和方法，对生物的各种类群进行命名和等级划分。瑞典生物学家林奈将生物命名后，而后的生物学家才用域（Domain）、界（Kingdom）、门（ Phylum）、纲（Class）、目（Order）、科（Family）、属（Genus）、种（Species）加以分类。最上层的界，由怀塔克所提出的五界，比较多人接受；分别为原核生物界、原生生物界、菌物界、植物界以及动物界。 从最上层的“界”开始到“种”，愈往下层则被归属的生物之间特征愈相近。共有七大类，分别是：界门纲目科属种。

**Comment by heshenxian1** [comment]
自问自答的思考——

怎么能更好分类，怎么利用分类改善自己信息加工的质量和速度？
隐喻和修辞对分类有什么帮助？范畴就是研究分类的认知科学视角。


你关于分类的认知雪球是啥样的？
你对分类的最小全局认识如何，有啥高阶模型和实践策略？
既然修辞故事逻辑再维特根斯坦那里是相通的，那你的确没必要纠结范畴。

关于分类或范畴的学习，不妨按阳老师的高阶模型学习法 走一遍试试。
[高阶模型学习法 - 阳志平的网志](https://www.yangzhiping.com/column/High-order-model-learning.html

范畴，分类，也就是好的心智习惯中的信息整理那一步的改善。范畴的高阶模型有原型范畴论和社会认同论，如何把它内隐呢？


之前佳文整理了阳老师谈学习博客的文章列表，我在此基础上做了一个分类示范，有个人理解的深浅轻重。这是一种分类方式，还可以有其他的。不断练习，不断优化，不求完美，只求进步。

[学习 | 02 Season | 整理阳老师谈学习的文章列表 · Issue #26 · heshenxian1/OpenMindClass](https://github.com/heshenxian1/OpenMindClass/issues/26

**Comment by heshenxian1** [comment]
阳志平的几段对谈灌水，可作为参考，启发引子

> 图书馆员的训练第一课就是编目、文献学、目录学。
> 其实都是信分的古代版训练。
> 老毛曾经有过图书馆员的训练哦。
> 知识结构上是具备的[偷笑]
> 
> 李彦宏也是这个专业出身的。
> 嗯，老毛是典型的利用信息不对称套利。


**

> **逻辑哲学论的评语，分类的升级，就是对世界认知的升级**


> 在对待【高阶模型】一事上，我们人类这种裸猿最容易犯的错误是，追求模型的数量，却不重视模型的内隐。人类大脑会先天地排挤各种模型。我们人类几千年演化，**今天我们习以为常使用的模型，本质上，其实都只跟三件事相关：命名、分类、变形。** 但，越来越多的人追求所谓的模型数量，似乎越多越智慧。……


命名、分类、变形。
命名、分类、变形。
命名、分类、变形。
—— 是啊，命名，分类，变形，就是改善心智习惯，提高学习能力的关键所在。
