### ISSUE TITLE
线下 | 20190316杭州线下书友会沙龙

### ISSUE THREAD

**Issue by bravejiawen** [heshenxian1/OpenMindClass#28]
## 20190316杭州线下书友会沙龙
![](https://user-images.githubusercontent.com/20290108/49428682-a869ac00-f7e1-11e8-898c-9730069366da.png)
> 行走江湖，总要有宝剑傍身。磨一把高效学习的利剑，静夜里伴你所向披靡。

## 活动信息
* 开智越读书友沙龙

第三季开智沙龙的聚会主题，**费曼技巧**，融合了具身认知和行动学习等内容。

费曼技巧的灵感源于诺贝尔物理奖获得者理查德•费曼（Richard Feynman），运用费曼技巧,你只需花上20分钟就能深入理解知识点,而且记忆深刻,难以遗忘。

费曼技巧的4个步骤：
**一、选择一个概念。**
选一个你想弄明白的概念，写在空白的笔记本或者纸的最上面。

**二、解释这个概念。**
把解释这个概念的东西写成一句话，就像你在告诉一个完全不知道这个领域的菜鸟一样。这一步可以让你在阐释这个概念的过程中，可以让你明白你有没有搞懂这个概念，并在这个过程中加深对这个概念的理解。

**三、解释不了？**
当你发现你没办法解释的时候，回到书上面去，或者找同学、找老师、找已经懂的人，把书上的概念再重新研究一遍，直到你能在纸上流畅地把这个概念解释出来。

**四、简化语言、学会类比。**
如果出现一个很学术的或抽象的词语的时候，试着要么平实化词语，要么学会用别的东西来类比它

**届时，每个人带上一个概念，按照费曼技巧，选一个你想弄明白的（让自己做一遍，或者想让其他人一起做一遍。）每一位参加前都自选一个概念做准备，利用面对面机会，真正的教中学，可以把三个月的学习穿过自己的身体。**

* 时间：03月16日（周六）13:30-17:00
* 地点：1013咖啡书吧
  ——地址： 文二路156号(近团校)
* 费用：场地费AA制，各自点单消费即可
* 联系人：小亦，
* 议程：
  
  * 13:00-13:30：签到，各自点单
  * 13:30-15:00：「费曼技巧」演示
  * 15:00-15:05：休息10分钟，合照
  * 15:06-16:00：主题对谈或小何彩蛋
  * 16:06-17:00：自由交流对谈

### 报名方式
确定参加的小伙伴，可在本issue下留言。

* 名号：
* 微信号：
* 联系电话：
* 预计到达时间：

**Comment by absir1949** [comment]
不好意思，周末有另外一个事情冲突，本期暂不参加。

**Comment by heshenxian1** [comment]
## 变形-费曼给你看


### 【引子】

什么是变形？变形是什么？你在日常生活里做过什么属于变形的动作？

变形，顾名思义，就是变化形状。在具体来说，就是你对一个物体对象，施加一个力，然后使得它的形状或形态发生变化。想想看，你是怎么使得一张纸变形的？你有没有玩过橡皮泥，它怎么在你的手里捏扁搓圆，把它变换出各种各样的形状？再比如摆在我们眼前这个可乐易拉罐，你能使它发生什么变形？



你有很多关于实物变形的经验，各种拉长缩短放大缩小；你也看过不少电影和小说，知道各种漫画人物比如孙悟空猪八戒米老鼠蜘蛛侠变形金刚，这些人物角色都是经过艺术变形得来的。可以说，每一个伟大的发明家，艺术家，创作者，都是变形的大师。那我们怎么能更系统地掌握「变形」这门技艺呢？



我们从生活经验里，从观察行动中获取很多信息，提炼很多套路，又从书本知识里获取很多模型，这些总结的套路模型、知识的精粹，我们要迁移灵活运用到生活工作中，就需要对它们进行变形因地制宜应用。


> 我们人类几千年演化，今天我们习以为常使用的模型，本质上，其实都**只跟三件事相关：命名、分类、变形。**



那今天我们在这里探索理解的「变形」，一起从具体到抽象，从已知到未知，把知识里的模型变形，应用得更好，深挖下去，这里面有非常多有意思的东西，我们可以用到很多高中初中小学学过的数学知识，帮助我们更好地理解「变形」，应用「变形」。



### 【正餐】

有两大类操作，可以帮助咱们更好地变形，一类是符号运算，一类是图形变换。

所谓符号运算，简单的有加减乘除四则运算，复杂的可以有多阶导数，微分积分等高等数学。而图形变换，有平移和缩放，旋转和对称，以及一系列的组合变换操作。



我们先来讲讲符号运算。

我们身处的世界非常复杂，有许多精微奥妙的地方值得探索。而另一方面，我们只用小学数学就可以很好地处理生活里面许多问题，得到非常多有益的启发。



你肯定听过朝三暮四这个成语故事，那你有没有想过朝三暮四和朝四暮三有什么差别呢？你在小学学加法的时候，知道了「交换律」，3+4= 4+3 =7 ，交换前后运算顺序，总和结果不变。而猴子的认知到人的心理感受上，他更喜欢朝三暮四，而不是朝四暮三，他更喜欢得到更多的趋势，更喜欢终点结果更好。你看，简单的加法，多想一下调整顺序得到结果是否一样，数学物理世界的加法交换律成立，那人性心理世界的加法交换律不一定成立。

怎么更好地做加法组合，交换律何时成立何时不成立，【A】+【B】≠【B】+ 【A】吗？多算一步做一下加法，你可能就更会分配资源，也更好利用大脑的认知偏差，还可以有更多各种收获。





下面我出一道题，你来做一下

> 问题：
>
> 《秘密特工》里，女特工测试冒充建筑师的男特工，问他西班牙台阶的由来。男特工说是该建筑师为了自己100岁的母亲。女特工说我数了下有135层。男特工说那一年建筑师35岁，所以加在一起是135。伶俐的女特工马上指出了漏洞，请问是什么？



 阿炳回答 : 那位妈妈65岁才生了建筑师。



对，漏洞就是处在这里了—— 女特工反问：建筑师妈妈65岁才生了他？—— 人的大脑很自然地会去做加法做乘法，但逆向过来做减法做除法的不多。100+35 =135 你很自然就点头算出来了，但如女特工般能够反问的恐怕没有几个人。100-35=65，人人都会计算。然而，愿意多算一步，做此减法，少之又少。

再换个角度理解，我们知道不少已知条件的表象，但往往忽视了已知条件背后的信息，那些数字、意义和其中的逻辑。我们把已知信息看成一个个ABCXYZ的符号，进行一下加减乘除的运算，就能获取你原本不知道的新信息。这类简单计算，小学数学的知识，你以为熟悉的运算，应用到生活的种种场景，你就是在对知识进行变形，获取新知。你再重温一下小学初中高中的很多数学知识，比如1加到100的高斯数列，比如更多更多排序变形，再到各种估算和算法，能带给你新启示。



加减乘除这类简单运算之外，我们还有更复杂一点的二阶操作，就像求导数一样。我们可以从里程、速度、加速度这些物理概念，重新理解增长。速度，是里程对时间的导数，加速度，是速度对时间的导数。而增长，可以是里程的积累，可以是速度的加快，可以是加速度的增大。加速度，就是速度的速度，可以看做是里程的二阶操作。提升加速度，我们可以用更短时间走得更远，更快到达终点。类似的，你的学习有成长加速度吗，除了原地踏步，或者线性增长之外，你的成长速率如何？类似微分导数，积分求和的数学运算，应用到生活工作的更多具体情境，会如何？带着符号运算这种变形工具，从数学到日常生活乃至更多未知领域，你去追问探索，看看能不能发现更多如学习的学习，认知的认知，行动的行动，概率的概率的深刻理解？



符号运算的两大类，一类是简单的四则运算，另一类是包括了求导微分等二阶操作的复杂运算。它们都是很好的变形操作方式。这种简单计算，多算一步，多连续进行应用，你能从中变形出许多别人视而不见的新知。



说了符号运算，再来看看图形变换，我们先来看眼前这张A4纸，你能对它做出多少种变换操作？

—— 嗯，我们可以用一张纸来打包，来折纸鹤，来卷成扩音器……各种对折，各种裁剪，还有卷起来。花式操作太多了。我们学初中几何的时候，还知道诸如全等，相似，轴对称，中心对称的概念，还知道平移，缩放，旋转，对称，螺旋等等图形变换操作。



那我们也可以把这些图形变换的操作，用在我们学到的概念术语，模型知识上。比如说，我们对某个知识 X 看成一个点，一个图形，在坐标轴上进行平移会如何？

某一个知识X，它在时间轴上平移会如何，在过去现在未来，知识X会一样吗，会不会变形了？它会有着同样的内容，不同的名字吗？某一个知识X，它在空间轴上平移会如何，在中国和在美国，在东方和西方都保持一样吗？除了把知识点在古今中外的平移，在不同学科领域中检视，我们还可以给知识点X照照镜子，X 在镜子中找出的另一个自己——Y是长啥样的？或者说在一条坐标轴上的两个端点，一对极端正反对立的概念A 和 B 是什么。可能我们可以从小孩子的对子歌中找到天对地，雨对风，大陆对长空。 从上下前后男左女右再到实力与运气，阴阳简繁这一类更复杂的术语概念。



找出一对对的X-Y，A-B，我们是不是就可以对知识点X本身理解更全面而深刻。把一个个知识模型，看成是一个个空间图形，进行各种平移，缩放，旋转，对称等图形变换，各种知识的变形敷衍出新知，我们能看到更多变化，把握更深层次的不变。



刚才说到的平移缩放旋转对称等等，都是对图形本身的操作变换，图形变换的另一大类，是对环境的变换，图形不变，参考坐标系变换了会如何？图形不变，外面打来的聚光灯变换了会如何？

比如说，你对一个圆上的点的描述，从直角坐标系的「(x,y)」变成「(ρ，θ)」，会如何？再想想，你有一个手电筒，打出一束光照在一个立方体上，不同的角度探照过来，落在一张A4上的投影会如何？类似，你对一个知识点，变换参考坐标系，得到的理解是不是会不一样了？你用不同角度给一个模型打光，或者用平行光替代聚光灯来打光，你是不是又得到一个不同的投影视图理解？



你看，当你对知识进行图形变换，你有两只手进行概念模型变形，一手你可以对知识图式本身进行变形，如缩放旋转，另一手可以对知识所在的空间环境本身变形，如坐标系变换，如投影变换。



### 【小结】

我们走到这里，就已经对「变形」本身有个初步而又系统的认识了，变形操作有两大类，一类是符号运算，一类是图形变换。符号运算大致两分，简单运算和二阶操作；图形变换亦可分为两种，一种直接变换图形本身，一种变换图形所在的参考环境。

无论是符号运算还是图形变换，我们都可以从熟悉的小学初中高中的数学物理知识获得启发，更深入进阶的大学物理和高等数学，同样也能提供给你我丰富的「变形」操作工具。



希望你能从更多「变形」的探索实践中，获得更多新知和乐趣，把你发现的有趣例子和心得收获告诉我。


## ChangeLog
- 20190319 v2.0 整合修改
- 20190317 复盘周六费曼过程，整理补充概念卡片

**Comment by alissli** [comment]
名号：aliss

---
## 慢空间
![IMG_2810](https://user-images.githubusercontent.com/23351109/54477791-0167c800-4846-11e9-8d21-06e2ecb92b1b.jpg)
书与做旧的古木色桌椅，击中了我。坐在楼下用餐，想有一家这样的咖啡馆的念头紧紧攫住自己。这样的空间，看着时间静静流淌，即是幸福。

## 费曼技巧

从费曼技巧入手，第三次越读会的主题渐入佳境。

何教解释何为变形：图形变换与符号运算。几番讨论下来，尽管初衷并非解释出处之原意，却对理解其源头，带来了启发。假如高阶模型是人类绘制大脑中的世界模型时，借用的各种镜头，它们所做的操作无非是「命名」、「分类」与「变形」。

从《三生有幸》入手，陈铭欲言「分类」，频频用两性的刻板印象举例，渐现这半年的认知拓展。

小奕描绘了一张「价值观」清单，在智友的提问与建议之中，做了大幅度修改。

Aliss从叙事学的「自由间接体」入手，欲呈现小说写作的技艺，却忘记用人去串联切入，更容易引起受众的兴趣。

青竹呈现职业困惑，从启发式问题和可执行层面的建议，重新思考问题。

主书记员阿炳，小结中闪现职业选手智慧的光芒。


- 费曼技巧的回顾：

   - 如何选取例子。你想讲的例子，能否更好的帮助别人理解你所解释的概念？
   - 费曼技巧检验你对某个概念的理解，过程中的有效反馈，给讲述人提供丰富的信息，加深对概念的理解。当然，假如对方完全没有理解，说明自己还需要深入的学习。

## 彩蛋-学习的最小全局认识

从时间、空间、变量关系去组织阳老师博客中「学习」主题，小何教练绘制了一张「学习」的知识图谱。

- 启发性问题
   - 小何教练的这个行为是否可以直接模仿？

## todo
- 阅读《别闹了，费曼先生》
- 阅读《转折点》
- 阅读《全局学习法》

## Changelog
1. 2019-03-16 第一版

**Comment by huangyu9887** [comment]
明天有事，祝大家聊得开心！

**Comment by bravejiawen** [comment]
## 会议记录 
by 阿炳
20190316 开智小聚 

- 闲谈
  - zotero，工作流，量级影响，
  - 育儿，母性没变，父性变化
- 费曼技巧
  - 何：变形
    - 于物体：橡皮泥，纸，施加力，变化形状。
    - 于模型：
      - 图形操作，平移，对称，旋转；例子：朝三暮四；正反。等，分形，补，镜像，螺旋，点对称。
        - 群论
        - 时空平移
      - 符号运算，加减。对已知信息的操作，加法与减法，乘与除，逆向操作。例子：特工100+35；二阶操作，导数，积分，比率，平方，根
        - 但这个算是变形么，更多是逆向思考吧。 
      - 实体，数字，图形 
    - 黎：命名分类，产生新信息；符合运算与图形可转化，模型的简化；
  - 分类
    - 比如三生有幸，因为幸福已经很难概括描述各种情况，模糊，就需要做出分类。比如三种幸福，如心流，，，  幸福定义不了，太粗，需要分类来准确描述
    - 经济成本原则，基本层次的分类。。。
    - 通过分类来更好理解判断与处理之类。。。
    - 调整分类颗粒度，上下级，数量，（又是变形了。。。）
  - 命名
    - 先分类，后命名；解释；猴子；儿童认知；颜色；
  - 价值观
    - 比如职业选择，看重什么因素，A还是B。情境中做选择时的标准。稳定与混乱的价值观。
    - 怎样形成自己稳定的价值观？黎：用内在动机来解决价值观判断的问题
    - 多层次的行为，多重因素影响，并不单纯依赖价值观来判断
    - 用“偏好”来代替价值观
    - 行动建议：把自己价值偏好的词罗列出来。
    - 事实、感觉、观点区分，相互影响与转化
  - 自由间接体
    - * [自由间接文体（Free Indirect Style ）](http://www.bimuyu.com/blog/archives/89668864.shtml)
    - * [从自由间接体谈起，福楼拜的客观叙述及其他_乔衍_新浪博客](http://blog.sina.com.cn/s/blog_4af30fa80102y1oo.html)
    - 何：引用举例的名字，中文文本；
    - 陈：上帝视角，缩进视角，从神变成人，客观描述--讲述心理--朋友视角
    - 应用可以在社会意向性？推测和理解么，，，
  - 职业困惑与目标
    - 价值观，活杂，学习，信息量与决策
    - 了解行业，公司发展与个人方向的一致性再做选择；压力测试，大量练习，参与系统学习与考试。（可以想想如何打广告，困惑中的职业人）
- 总结
  - 概念滚雪球，
  - 分类变形，产生新信息（熵减），
  - 用以解释的例子需挑选（如何来），呈现信息时考虑接受者的背景知识，如何更好的理解；积累虚构故事，模型；
  - 概念的表述，如何关联清晰
  - 感觉、理解与表达出来的不一样，自己原来会把理解或接触到的一个概念套用到很多地方去
  - 能更明确自己困惑或不满意的点

**Comment by sarsbiker** [comment]
> 提前没准备，只作了旁观者参与，记下些许片段

### 概念分享环节
- 小何同学分享了【变形】
  - 以橡皮泥和纸张为例讲物理上的变形，延伸到模型的变形。何之变形与阳老师略有不同，分为图形操作与符号运算。图形操作就如平移、旋转、对称、镜像等，符号运算则有基础的加减乘除和二阶的导数、开方等操作。提了“朝三暮四”与“通过135个台阶识别特工真假”两个例子做了讲解。
  - 不过对于此概念，大家疑惑还不少，比如黎黎同学提及模型不够简练，比如符号运算与图形其实可互相转化。
  - 分享过程中还有以下关键词：图形、实体、逆向操作、新信息、分形、正反、群论等。
- 陈同学分享【分类】
  - 分类是为了更好的理解与判断，当已有分类不能准确表述时就需要做区分。开场以《三生有幸》为例，幸福一词难以清楚概括，这时就分了心流等三种情况。受进化影响，我们通常只会用基本层次的分类，正因为如此，我们才需要根据情况调整分类层次/颗粒度，使用上位词或下位词。陈同学多次提及——描述时不用”男/女人如何如何”而是“XX人如何如何”。
  - 交流分享时也讨论到命名，有个小共识就是分类先于命名。当时提及的关键词有认识颜色、儿童认知、猴子。
- 小亦同学分享【价值观】
  - 价值观概念倒比较好理解，人们在情境中做判断时，用以参考的标准，比如找工作时更看重薪资待遇还是自由时间等。概念之后的问题是价值观的影响以及价值观的形成与稳定。（正是变量三范式耶~）
  - 大家讨论并分享了想法与建议：1，行为很复杂，受多重因素影响，并不单依赖价值观做判断；2，建议用内在动机来解决价值观判断的问题，避免问题复杂化；3，用“偏好”代替“价值观”一词；4，罗列体现自己价值偏好的词。
- 黎黎同学分享了【自由间接体】
  - 这是《小说机抒》中特别提及的一种写作技巧，大意是在第三人称视角写作中，切换到角色的视角叙述。在网上找了两篇谈此技巧的文章：
       * [自由间接文体（Free Indirect Style ）](http://www.bimuyu.com/blog/archives/89668864.shtml)
       * [从自由间接体谈起，福楼拜的客观叙述及其他_乔衍_新浪博客](http://blog.sina.com.cn/s/blog_4af30fa80102y1oo.html)
  - 因为缺乏背景知识，大家没有过多讨论，小何同学建议解释用的例子可以尝试找中文文本及中文名或许更易懂。黎黎同学最后提到这种技巧或许可提高社会意向性，训练自己做推测。（期待实践成果）
### 杂谈
- 青竹同学的职业困惑
  - 青竹同学近期正遭遇职业困惑，没有分享概念，而是提出了自己的问题。青竹商科毕业，因兴趣而成为了灯光方向的软装设计师，然而所在工作室的老板（设计总监）却把兴趣转向了产品（工业）设计与生产。个人兴趣方向与公司发展出现不一致，且日常工作内容较杂、缺乏合适的导师。
  - 沟通之后同学们给了建议：1，小题大作；2，了解行业，理解行业/公司的运作机制；3，利用酷家乐等平台（有大量同行和业主）做模拟练习，做压力测试，提升专业技能；4，系统学习并通过考试（国内尚无标准）。
- 费曼技巧应用的效果
  - 阿炳同学作为旁观者，发现流程并没按理论上的费曼技巧来，不过大家都有收获，交流中有碰撞，每个人都加深了理解。但对于概念的共识，可能并没有达成，比如讨论许久变形，大家理解还不一样，讲述者必然想得更清楚。
- 另外聊了许多小话题，比如母性恒定而父性会因育儿而激发、zotero如何融入工作流、概念滚雪球

### 彩蛋
- 小何同学分享了对学习的全局认识，把元反空、时空变量、学习层次等模型都串联了起来。这块就等小何同学再次分享吧。

### 思考
- 费曼技巧也是“以教为学”的一种具体具体形式，即使没有完全按此来，只要与人交流、分享，尝试跟人解释，就会迫使自己去思考，加深理解。纵然现场没讲透，后续也会再研究，把“雪球变成圆的”。所以呢，还是要多线下聚，多交流也。

### changelog
- 20190316 用关键词记录
- 20190318 同步issue
