### ISSUE TITLE
积极心理 | 03Season | 建构-卡片集

### ISSUE THREAD

**Issue by heshenxian1** [heshenxian1/OpenMindClass#33]
积极心理学的前世今生，与心理学从二十世纪走向二十一世纪的研究主脉搏同频共振。同样地从本质主义走向可操作主义。「建构」二字，可以说是贯穿积极心理核心内容的钥匙。你我借着这个 issue， 将主题阅读中发现的种种「建构」，撷取一颗颗「建构」金句果实，串成丰美甜蜜的葡萄吧。

**Comment by alissli** [comment]
### 《情绪》关键词
整体论、涌现特性、简并、概念、分类、预测、情绪粒度、内感受、控制网络、
行动与意义、情绪
构建理论、情绪建构、社会建构、心理建构
群体思维、情绪变异性
情绪实例、情绪类别

**Comment by heshenxian1** [comment]
组块是成为专家的秘密。
而工作记忆的底层原理，不仅仅适用于学习，还可以用于情绪建构，这里面的底层都离不开「概念」。
「组块」「范畴」「概念」「图式」「框架」这些都是大脑运作机制的关键所在，也是《情绪》一书英文副标题所隐藏的秘密。

这篇关于工作记忆的文章，对学习和积极心理都极有帮助
[Working Memory: A Complete Guide to How Your Brain Processes Information, Thinks and Learns | Scott H Young](https://www.scotthyoung.com/blog/2019/04/24/working-memory/#07-01 )

其中「化焦虑为兴奋」的章节，提供一些有效细节技巧。这也**暗合大脑心智原理——反省心智的三个关键词，积极态度，策略，自我管理和监控。**

**Comment by heshenxian1** [comment]
### 建构理论*

情绪建构论隶属于一个更为广泛的传统科学理论，即构建理论。该理论认为，你的体验和行为是通过你的大脑和身体的生理过程实时创造出来的。构建理论的渊源非常古老，可以追溯到古希腊时代，当时著名的哲学家赫拉克利特有一句名言：

“人不能两次踏进同一条河流。”

因为有智慧的人会把一条不断变化的河流看成不同的水流。今天，**建构理论应用非常广泛，包括应用于记忆、感知、精神疾病，当然，也包括情绪。

#### 建构论的线索溯源

以概念为基础的人性建构。

- **多维分层的建构**
- **人工智能-深度学习的神经网络模型**

1. 记忆构建理论
2. 感知构建理论
3. 自我构建理论
4. 概念发展构建理论
5. 大脑发展构建理论（神经构建）
6. 情绪建构论



- 希腊人赫拉克利特认为人类思维在瞬间构建感知，就像无数的水滴构建一条河那样。赫拉克利特比柏拉图早了100年。
- 11世纪的科学家伊本·阿尔·海赛姆为科学方法的发展做出了重要贡献，他指出，构建理论认为我们通过判断和推理感知世界。
- 18世纪的哲学家，如大卫·休谟和伊曼努尔·康德则更赞同通过构建理论和感知来解释人类的体验。
- 19世纪，威廉·詹姆斯和威廉·冯特开始支持**构建理论。**正如詹姆斯所说的：“一门关于思维和大脑的科学必须能够证明思维的基本构成与大脑的基本功能相对应。”
- 詹姆斯和达尔文可以说是这场斗争的受害者，因为他们和情绪有关的看法被篡改了，他们的成果被布洛卡这样的科学家窃取了，后者宣称这是一场进化论的胜利……或者至少是进化本质论的胜利。
- 如今思维的构建观点越来越丰富。心理学家兼畅销书作家丹尼尔·L.沙赫特提出了记忆构建理论。现在，你很容易就能看到感知构建理论、自我构建理论、概念发展构建理论、大脑发展构建理论（神经构建），当然，还有情绪建构论。

—— 《情绪》

**Comment by heshenxian1** [comment]
## 《情绪》与建构主义

情绪建构论，是人性理论，也是心智理论。

**人类大脑是如何创造人类心智的。**



情绪建构论则打破了我们对常识的认知——你的大脑在无形中构建了你体验到的每件事，包括情绪。这种理论提出了一些我们不熟悉的特性，如**模拟、概念和简并**，而且它认为情绪构建是**整个大脑同时作用的结果。**



情绪构建一直延伸到了细胞层次。

【情绪架构，多层的建构——细胞层（生物），概念层（心理），文化层（社会）】

**社会构建理论承认文化和概念的重要性；**

**心理构建理论认为情绪是由人的大脑和身体内的核心体系构建的；**

**神经构建理论认为经验和大脑联结；**

**情绪建构论融合了这三种构建理论的所有要点。**




### 情绪建构论

**【情绪建构 = 神经建构 + 心理建构 + 社会建构】**

**【情绪现实 = 情感现实 + 概念形成 + 社会现实】**

**How Emotions are Made**

How 【XXX】 are Made



巴瑞特教授在本书中，博采众家之长，将基本情绪论、情绪评价论称为传统情绪理论；而**将心理建构论、社会建构理论以及近些年发展起来的神经建构论称为情绪建构论。**我们会发现，传统情绪理论与情绪建构论截然不同。



**社会构建理论承认文化和概念的重要性；**

**心理构建理论认为情绪是由人的大脑和身体内的核心体系构建的；**

**神经构建理论认为经验和大脑联结；**

**情绪建构论融合了这三种构建理论的所有要点。**



根据情绪建构论，情绪的炼成需要3个必要材料，因此我们需要知
道动物是否具有这3个材料。

**第一个材料是内感受：**动物有神经结构创造内感受感觉，并把这些感觉体验为情感吗？

**第二个材料是情绪概念：**动物可以习得纯心理概念，如“恐惧”和“快乐”吗？如果可以，它们可以用这些概念进行预测吗？它们能对感觉进行分类，最后得到和我们一样的情绪吗？

**最后一个材料是社会现实：**动物可以彼此分享情绪概念吗？它们能够把情绪概念传给下一代吗？




#### 巴瑞特教授建议

情绪管理三步曲：**身体预算平衡，提高情绪粒度，每天记录积极体验。**



> 实际上，要想控制你自己的情绪，你需要做的**最根本的一件事就是，让你的身体预算处于良好的状态。**
>
> ……
>
> 巧妙的情绪调节，都与**内感受网络和情绪粒度**相关。
>
> ……
>
> 什么是情绪粒度？就好比一个优秀的作家，其词汇量远远大于普通人；同样，情绪粒度足够高的人，往往拥有数千个情绪词汇来描述情绪；情绪粒度低下的人，往往只有数个词汇描述情绪。
>
> 你可以通过阅读小说、旅游等手段，不断提高自己的情绪粒度。
>
> ……
>
> 在提高了情绪粒度之后，另一个锤炼概念的方法是**每天记录你的积极体验。**
>
> 每当你做积极的事情时，你就可以对你的概念系统进行微调，强化关于积极实践的概念，让它们在你的思维模式中变得显著突出。





**人生的意义在于建构，建构来自你相信你的经验，这不仅包括外在的感受，也包括内感觉。**

你的学习，尤其是增加情绪粒度，会让你更好地描绘情绪光谱，而人类与环境的互动就构成了我们的社会现实。

**应用全新的人性观，尤其是身体和社会之间存在的可渗透边界观点，设计一个生活食谱**.。

在这个食谱中，主要的食材就是你的身体预算和你掌握的概念。



以前种种心理疗法都尝试正面突破马其诺防线。巴瑞特教授的研究却告诉我们，你越将情绪看作一种在大脑中存在的特定结构，你越可能难以改变。巧妙的情绪调节，都与内感受网络和情绪粒度相关。巴瑞特教授将其总结为**情感现实主义、概念与社会现实**三者。

**Comment by heshenxian1** [comment]
#  F(情绪建构）=f( 神经建构，心理建构，社会建构)
情绪建构理论融合了其他建构理论的内容，如社会建构理论主要研究社会价值观和兴趣，确定我们在世界中的感知和行为方式。


情绪构建一直延伸到了细胞层次。

【情绪架构，多层的建构——细胞层（生物），概念层（心理），文化层（社会）】

> **社会构建理论承认文化和概念的重要性；**
>
> **心理构建理论认为情绪是由人的大脑和身体内的核心体系构建的；**
>
> **神经构建理论认为经验和大脑联结；**
>
> **情绪建构论融合了这三种构建理论的所有要点。**







#### 社会建构理论

【社会角色，身份认同，社会范畴，群体认同】

就情绪而言，社会建构理论探讨的是社会角色或者信仰是如何影响情感和感知的。

社会建构理论通常认为情绪和生物学无关；相反，根据社会建构理论，出现哪种情绪，取决于这个人当时所拥有的不同的社会角色。社会建构理论关注的是你周围的社会环境，一般不考虑环境对大脑回路的影响。



#### 心理建构理论

低维的知觉，感觉，想法；高维的推理，学习，判断

—— 感知，情感，认知（意义），「知情意」有着同样的底层机制和建构原理。



另一个建构理论就是心理建构理论，该理论把关注的焦点放在了人的内在，认为人的知觉、想法和感觉是由更基本的部分构成的。19世纪的一些哲学家把心理看成一个巨大的化学组合，就像原子组合构成分子一样，更为简单的感觉组合构成了思想和情绪。也有一些哲学家把心理看成一套多用途的零部件，就像乐高积木，可以组合在一起形成各种心理状态，如认知和情绪。



心理学家威廉·詹姆士认为，每个人截然不同的情绪体验是由一些常见的感觉构成的。“情绪产生的大脑过程不仅类似于普通感觉的大脑处理过程，而且它其实就是普通大脑过程的不同组合形式。”



在20世纪60年代，心理学家斯坦利·沙赫特和杰罗姆·辛格做了一个非常有名的实验，在受试者毫不知情的情况下给他们注射了肾上腺素。因为所处环境不同，受试者中有人表现出愤怒，有人表现出兴奋。在所有人中，愤怒或者兴奋的实例并没有显示出任何的因果机制——这与传统情绪观形成了鲜明对比。


**情绪是被创造出来的**，而不是被激发出来的；人们的情绪多变，且不存在情绪指纹；**原则上来讲，情绪、认识以及知觉没有什么不同。**


#### 神经建构理论

似乎这些相同的构建原则都适用于大脑的物理结构，即神经构建。你可以想象一下由一个突触连接的两个神经元。

显然这些脑细胞是客观存在的，但是我们却没有一个客观的方法能说明这两个神经元属于同一个“回路”或者同一个“系统”；或者两个神经元分属不同的独立回路，但可以彼此调节。


大脑互连并不是你的基因单独作用产生的必然后果。我们都知道，经验是一个影响因素。在不同的环境中，你的基因或打开或关闭，包括那些形成大脑连接的基因。（科学家把这种现象称之为“可塑性”）这意味着，当其他人以某种方式和你谈话或者对待你时，你的某些突触会真实形成。换句话说，情绪构建一直延伸到了细胞层次。


脑的这种宏观结构很大一部分是由遗传决定的，但微观连接则不是。

因此，过去的体验能够帮助你确定对未来的体验和看法。**神经构建理论**也解释了人类婴儿为什么在出生时无法识别人脸，但几天后他们就培养了这种能力。它也解释了幼儿时期文化体验是如何塑造不同的大脑联结的。早期的文化体验包括你的照顾者和你的身体接触的频率，比如你是独自睡在摇篮里还是和家人睡在一张床上。

**【神经建构论——神经可塑性，全脑工作站，发展心理学】




#### 情绪建构综合-世界大脑一体化

神经系统科学的构建理论。

**词汇孕育概念，概念推动预测，预测调整身体预算，身体预算确定你的感觉。**



**根据情绪建构论，大脑和世界之间的分界线是可以渗透的，也许根本就不存在。**你的大脑的核心系统以多种不同方式组合，构建你的感知、记忆、想法、感情以及其他心理状态。



通过内感受，你的大脑为你构建了生存环境。

**在你的大脑为你塑造世界的同时，外部世界也在连接你的大脑。**



**大量感觉输入中**，外部世界播种了你最初的概念，因为你的大脑已经把它自己和你周围物理世界的现实绑在了一起。这就是婴儿大脑能够逐渐认出人脸的原因。

随着你的大脑的发展，你开始学习词汇，你的大脑把它自己和社交世界连接起来，你开始构建纯心理概念，这些基于你的文化产生的概念似乎就存在于外部世界中，但是**它们实际上是你的概念系统构建出来的。**



文化帮助你连接你的大脑，你的某些行为方式连接了下一代人的大脑。

你的构建不是任意的，你的大脑（以它创建的思维）必须和一些重要社会现实保持联系，其目的是为了保持你的身体健康，充满活力。



构建会让你可以重绘国家版图、重新定义婚姻，去确定谁值得、谁不值得。你的基因让你拥有了大脑，大脑把它自己和它所处的物理和社会环境连接到一起，你所属文化中的其他人和你一起构建了生活环境。**创造思维只有一个大脑是不够的。**

—— 文化，大脑的共创。


情绪建构论也对理解个人责任提供了一种全新的思考方式。

**Comment by heshenxian1** [comment]
### 《认知治疗技术 》与建构

【认知治疗】的最底层基石，归因解释的所有起点——**想法并非事实**。

想法并非事实；想法并非事实；想法并非事实。



> 认知模型是最具建构性的。
>
> **“人人都是科学家”**的模型为基础的心理治疗认知模型
>
> **相信不等于真相**
>
> 认识到想法并非事实是帮助患者建构事件的 其他可能解释的起点。

认知治疗方法是建构的，因为它承认个体对于 现实的建构或解释可能基于独特的信息、个人化的范畴或认知偏差。



#### 认知治疗的技术

认知治疗的一些概念源于胡塞尔(Husserl, 1960)关于现象学的一些早期的哲学思考。事 实上，认知治疗就是现象学，它描述并分析经验的范畴。认知治疗先驱贝克(Beck)与哲学家 胡塞尔之间的区别就在于贝克提出了一种通过检查人对现实的想法来检验其现象学经验的 方法。

“现实”是一个开放系统。“认识者”——治疗师和患者永远无法拥有全部事实，因此在这种意义上来说认知模型是最具建构性的。对信息的检验也无法穷尽。经验世界中的认 识是一种带有更多可能性而不是确定性的陈述。预测总是以不完全的信息为基础的。承认 推论性思维总是不完全的、不确定的和随机的，是认知治疗师的一个基本观点。


心理治疗的认知模型是以乔治•凯利(George Kelly)在1955年提出的**“人人都是科学家”**的模型为基础的。凯利的模型认为人们可以确认自己的个人“建构”或信念并去检验它们。而当前的认知模型是由贝克和他的同事进一步发展的，强调寻找信念的“矛盾”和“反证”的科学思维方 式，也就是说，强调评价某个信念如何被证明是错误或不合适的，而不仅仅去找出那些支持的证据(参见Popper，1959)。抑郁个体可能会集中选择那些与他们的抑郁情感的负性状态相一 致的信息，而忽略掉那些不一致的有关证据。认知模型对这两方面的证据都要进行评价。

#### 技术:从损失与冲突中寻找新的意义和机会

【重新认识资源，重新定义「损失」和「错误」，冲突与矛盾】
“在消极的处境中寻找积极的成分”这个最基本的观点

**最基本观点——“在消极的处境中寻找积极的成分”


损失与冲突是生活中不可避免的一部分。当我们意识到这些损失和冲突可能是痛苦的 和需要明显调整的时候，同样可让我们发现这些损失也提供了重新建构意义的机会，提供了打开新的意识的机会，或者对个人成长提供了的新的挑战。



- 例子

一个正经历离婚的患者可能会报 告说她很抑郁，因为她的生活中丧失了一段亲密关系和稳定的习惯。但是离婚同样可以：

（1) 提供一个重新认识和定义个人价值中的依恋与亲密关系的机会；

（2)创造了与朋友或其他亲 密个体建立新的关系的机会；

（3)促进了她个人工作业绩的提升，增进与他人交往的个人经验。

因此，我们应该鼓励患者考虑机会、挑战，以及由当前情景中可能获得的意义，而不是将 注意力投向挫折的消极面。

认知治疗的创始人之一，**维克多•弗兰克(Victor Frankel)**在他一本著名的著作《人类对于意义的追求》中描述了这一观点。在这本书中，他描述了纳粹死亡集中 营里的生活，在那里，寻找生存的意义成为了惟一的应对方式。



“在消极的处境中寻找积极的成分”这个最基本的观点，让我有了更加深刻的认识。
