### ISSUE TITLE
【FAQ】疑问记录

### ISSUE THREAD

**Issue by absir1949** [heshenxian1/OpenMindClass#4]
* 当前这个主题我已经阅读过了，我们当前应该的策略是？为什么？

* 除开当前这个月主题之外，我有另外的阅读兴趣，如何平衡？

请 @heshenxian1 帮忙解答下疑问。

**Comment by heshenxian1** [comment]
@absir1949 

#3 这是初步的主题设置示范，个人也打算将「创造」作为第一个季度的主题阅读。

你多从「可供性」而非「可用性」的角度考虑开智正典读书会的运行和使用吧。

初读的可以专心只读一章，重读的可以再次抽样阅读和结构阅读以及批量阅读。一个读书会有不同层次的阅读者，输出你的思考和理解，输出你的探索和行动就好。

还是那句话：

> 开智学习者最反常识的地方。自己只精读一章，然后借助其他同学的精读，刺激自己。从而得以保持大时间周期的进步。


1. 若这个主题相关几本书，你已经阅读过，你输出了哪些卡片，做了什么反常识卡，术语卡，人名卡和行动卡？这些卡片你有没有去整理或者编排组合。你有没有就这个主题阅读后，就一本书或三五本书串联，输出几篇读书笔记？

2. 经典需要重读，你重读了哪些章节，当你再重读精度时，你有没有发现什么是之前视而不见的？你能就这个主题，提出些什么问题？我问几个基本问题：我能从这几本书中挖掘出有「生活价值」的知识点？我怎么把《创新算法》联系到我的工作学习中来？比如用「时空变形」，我能串联起哪几本书，哪几个章节，延伸拓展出什么新思考和新的行动点？

3. 设计「季度主题」，一个方面是减少大家的认知负荷，减少年度阅读关键词，；另一个是兼顾你的其他阅读兴趣，你若学有余力，可以私下进行其他领域的阅读，也可以在开智书友会中推荐其他主题或者提问。若你的阅读兴趣恰好与当前主题相关， 那还有什么其他书籍或者案例，你认为与这个主题有帮助，值得延伸阅读的呢？

4. 若当前主题已有相关了解，那进一步向下能不能发展更多实践策略，向上能不能高阶拓展，进行比如「元反空」「演绎法」「时间空间变量」框架的梳理，生成自己的知识树？

一年四个主题关键词，一个季度核心三四本书，结合卡片大法输出，搭配一季度一场线下活动，这是最小框架，最小核心行动。这样的认知负荷和阅读节奏都可接受，每个参与开智正典读书会的小伙伴应该都能接受。这是标准配置和基本内核，更多拓展可以依据书友的主动性和参与度，自主发挥。

按「721」分配原则，开智正典主题阅读可以是你 10% 的精力不求目的自由探索的那通识部分，也可以是你个人特别关心要深入挖掘拓展的， 你可以做更多其他阅读和实践。这个平衡度，看每个人自己把握。

**Comment by absir1949** [comment]
谢谢 @heshenxian1 解答疑惑。

疑惑已解除。
